import { useEffect } from "react";

const titles = { privacy: "Confidentialité et données personnelles", terms: "Conditions d’utilisation", legal: "Informations sur l’éditeur" };

export default function LegalPage({ section = "privacy" }) {
  const title = titles[section] ?? titles.privacy;
  useEffect(() => { const previous = document.title; document.title = `${title} · AthleteOS`; return () => { document.title = previous; }; }, [title]);
  return <main className="min-h-screen px-4 py-8" style={{ background: "var(--c-bg)", color: "var(--c-text-1)" }}>
    <article className="max-w-3xl mx-auto space-y-6 leading-relaxed">
      <a className="btn-secondary inline-flex" href="/">Retour à AthleteOS</a>
      <header><p className="meta-text">ATHLETEOS · VERSION DU 8 SEPTEMBRE 2026</p><h1 className="text-2xl font-bold mt-2">{title}</h1></header>
      <nav aria-label="Informations légales" className="flex flex-wrap gap-3">
        {Object.entries(titles).map(([key, label]) => <a className="underline py-2" key={key} href={`/?legal=${key}`} aria-current={section === key ? "page" : undefined}>{label}</a>)}
      </nav>
      <aside className="rounded-xl border p-4" style={{ borderColor: "var(--c-border)" }}>
        Notice de la version pilote. Les informations d’exploitation, les durées de conservation et le cadre des données de santé doivent encore être validés avant une ouverture commerciale. Cette page ne constitue pas une certification de conformité RGPD.
      </aside>
      {section === "terms" ? <>
        <section><h2 className="text-lg font-semibold">À quoi sert AthleteOS ?</h2><p>AthleteOS aide les clubs d’athlétisme à organiser leurs séances, leurs groupes et le suivi de leurs athlètes. Chaque coach garde le choix de sa méthode et des outils activés. Les indicateurs et alertes ne remplacent ni le jugement du coach ni un avis médical.</p></section>
        <section><h2 className="text-lg font-semibold">Compte et invitations</h2><p>Utilise une adresse email qui t’appartient et garde ton mot de passe confidentiel. Un compte est rattaché à un club. Une invitation ne transfère pas automatiquement un compte vers un autre club. Le responsable attribue les rôles ; partager une invitation coach donne un accès au staff et doit rester limité à son destinataire.</p></section>
        <section><h2 className="text-lg font-semibold">Utilisation responsable</h2><p>Ne partage que les informations nécessaires au suivi sportif, avec les personnes autorisées. Ne dépose pas de documents médicaux ou de contenus concernant des tiers sans cadre approprié. Le club doit organiser l’information des athlètes et, lorsque nécessaire, de leurs représentants légaux.</p></section>
        <section><h2 className="text-lg font-semibold">Disponibilité et sauvegardes</h2><p>Une connexion est nécessaire pour synchroniser les données. Une action n’est enregistrée que lorsque l’application en confirme le succès. En cas d’erreur, conserve ta saisie et réessaie. La version pilote ne comporte pas de garantie contractuelle de disponibilité ; cela ne limite pas les droits légaux applicables.</p></section>
        <section><h2 className="text-lg font-semibold">Arrêt de l’utilisation</h2><p>Tu peux télécharger tes données et demander la suppression de ton compte depuis Réglages → Compte. Le dernier responsable doit d’abord transmettre la responsabilité du club. Les contenus collectifs nécessaires au club peuvent être conservés et réattribués ; la confirmation de suppression précise la portée de l’action.</p></section>
        <section><h2 className="text-lg font-semibold">Offres payantes</h2><p>Aucun abonnement ni paiement n’est activé dans ce parcours. Une offre payante devra présenter ses prix, modalités de résiliation et conditions applicables avant toute commande.</p></section>
      </> : section === "legal" ? <>
        <section><h2 className="text-lg font-semibold">Éditeur</h2><p>AthleteOS est un projet indépendant dédié à l’athlétisme. L’identité juridique, les coordonnées de publication et, le cas échéant, les identifiants d’entreprise sont en cours de confirmation. Ces informations doivent être complétées avant la commercialisation.</p></section>
        <section><h2 className="text-lg font-semibold">Services techniques</h2><p>L’interface est déployée sur Vercel. Supabase fournit l’authentification, la base de données et le stockage des fichiers. Le fournisseur d’envoi des emails reste à configurer. La région d’hébergement et les garanties contractuelles relatives aux éventuels transferts doivent être vérifiées avec les comptes d’exploitation.</p></section>
        <section><h2 className="text-lg font-semibold">Signaler un problème</h2><p>Pour une difficulté d’accès ou une donnée incorrecte, contacte d’abord le responsable de ton club. Le contact public de l’éditeur sera affiché ici après validation des coordonnées de publication.</p></section>
      </> : <>
        <section><h2 className="text-lg font-semibold">Données utilisées et finalités</h2><p>Le compte utilise une identité, une adresse email, un rôle et un rattachement au club. Selon les outils activés, le suivi comprend des séances, présences, feedbacks, performances, objectifs, réponses wellness, blessures, messages et documents. Ces informations servent à organiser et suivre la pratique de l’athlétisme.</p></section>
        <section><h2 className="text-lg font-semibold">Qui voit quoi ?</h2><p>Les accès dépendent du club, du rôle et des règles du module. Les coachs accèdent au suivi du club ; certaines réponses wellness peuvent être réservées au head coach selon la configuration. Les messages sont accessibles à leurs participants. Les fichiers privés sont fournis au moyen de liens temporaires. Les affectations « Mes athlètes » organisent le suivi, sans créer à elles seules une barrière de confidentialité entre coachs.</p></section>
        <section><h2 className="text-lg font-semibold">Wellness, blessures et mineurs</h2><p>Certaines réponses peuvent révéler des informations de santé. Le club doit définir et documenter la base légale et la condition autorisant leur traitement, limiter leur collecte et informer les athlètes avant la saisie. Activer un module ou accepter les conditions générales ne vaut pas consentement aux données de santé. Un cadre adapté aux mineurs doit être défini avec le club avant leur inscription.</p></section>
        <section><h2 className="text-lg font-semibold">Tes droits et tes données</h2><p>Dans Réglages → Compte, tu peux modifier ton identité, changer ton adresse après confirmation, télécharger un export personnel et demander la suppression de ton compte. Pour une rectification du dossier sportif, une demande de limitation, d’opposition, d’accès complémentaire ou d’effacement, contacte le responsable du club. Une demande ne doit pas nécessiter d’envoyer ton mot de passe.</p></section>
        <section><h2 className="text-lg font-semibold">Conservation</h2><p>Les données de suivi restent liées au compte et au club tant qu’elles ne sont pas supprimées selon les parcours disponibles. La suppression du compte ne supprime pas le club ni tous ses contenus collectifs. Les copies de sauvegarde suivent leur propre cycle de conservation. Les durées précises par catégorie, la gestion des comptes inactifs et la procédure après restauration restent à formaliser avant commercialisation ; aucune durée non configurée n’est promise ici.</p></section>
        <section><h2 className="text-lg font-semibold">Stockage sur l’appareil et notifications</h2><p>Le navigateur conserve des éléments nécessaires à la session, à tes préférences et au fonctionnement de l’application installable. Les notifications Push nécessitent ton autorisation et peuvent être désactivées dans l’application ou dans les réglages du navigateur. Évite de partager un appareil connecté à ton compte.</p></section>
        <section><h2 className="text-lg font-semibold">Surveillance des erreurs</h2><p>Lorsqu’un service de diagnostic est configuré, l’application prépare des rapports techniques en masquant les contenus métier, les messages libres, les coordonnées et les jetons de connexion. Les captures vidéo de session ne sont pas activées par cette configuration. Les conditions du prestataire et la durée de conservation doivent être validées avant activation.</p></section>
        <section><h2 className="text-lg font-semibold">Réclamation</h2><p>Tu peux t’adresser à une autorité de contrôle compétente, notamment l’<a className="underline" href="https://www.autoriteprotectiondonnees.be/citoyen" target="_blank" rel="noreferrer">Autorité de protection des données belge</a>.</p></section>
      </>}
    </article>
  </main>;
}
