BEGIN;

-- ---------------------------------------------------------------------------
-- Planning : provenance, séries et modifications sûres
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.session_series (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  club_id integer NOT NULL REFERENCES public.clubs(id) ON DELETE CASCADE,
  title text NOT NULL,
  time text NOT NULL,
  type text,
  category text,
  training_focus text,
  duration_minutes integer NOT NULL,
  description text,
  instructions text,
  interval_weeks integer NOT NULL DEFAULT 1,
  weekdays smallint[] NOT NULL,
  starts_on date NOT NULL,
  ends_on date,
  occurrence_count integer,
  target_group text,
  created_by integer NOT NULL REFERENCES public.users(id),
  updated_by integer REFERENCES public.users(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT session_series_interval_check CHECK (interval_weeks IN (1, 2)),
  CONSTRAINT session_series_weekdays_check CHECK (
    cardinality(weekdays) BETWEEN 1 AND 7
    AND weekdays <@ ARRAY[1,2,3,4,5,6,7]::smallint[]
  ),
  CONSTRAINT session_series_bounds_check CHECK (
    ends_on IS NULL OR ends_on >= starts_on
  ),
  CONSTRAINT session_series_count_check CHECK (
    occurrence_count IS NULL OR occurrence_count BETWEEN 1 AND 104
  ),
  CONSTRAINT session_series_time_check CHECK (time ~ '^(?:[01][0-9]|2[0-3]):[0-5][0-9]$'),
  CONSTRAINT session_series_duration_check CHECK (duration_minutes BETWEEN 1 AND 1440)
);

ALTER TABLE public.sessions
  ADD COLUMN IF NOT EXISTS series_id bigint REFERENCES public.session_series(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS series_original_date date,
  ADD COLUMN IF NOT EXISTS source_kind text NOT NULL DEFAULT 'individual',
  ADD COLUMN IF NOT EXISTS target_group text,
  ADD COLUMN IF NOT EXISTS parent_session_id integer REFERENCES public.sessions(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS updated_by integer REFERENCES public.users(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();

DO $$ BEGIN
  ALTER TABLE public.sessions ADD CONSTRAINT sessions_source_kind_check
    CHECK (source_kind IN ('individual', 'group', 'series', 'group_series', 'exception', 'duplicate', 'template'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE INDEX IF NOT EXISTS sessions_series_date_idx
  ON public.sessions (series_id, session_date);
CREATE INDEX IF NOT EXISTS sessions_club_target_group_date_idx
  ON public.sessions (club_id, target_group, session_date)
  WHERE target_group IS NOT NULL;

-- Étend les RPC historiques sans créer un second moteur de séance. Le groupe
-- choisi par le coach devient une provenance explicite, tandis que les
-- créations athlète et les séances sans groupe restent individuelles.
CREATE OR REPLACE FUNCTION public.create_session_with_athletes(
  p_session jsonb,
  p_athlete_ids integer[],
  p_idempotency_key text DEFAULT NULL
) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $$
DECLARE
  v_user_id integer := public.get_my_user_id();
  v_club_id integer := public.get_my_club_id();
  v_role text := public.get_my_role();
  v_my_athlete_id integer := public.get_my_athlete_id();
  v_cached jsonb;
  v_session_id integer;
  v_result jsonb;
  v_target_group text := CASE WHEN v_role IN ('head_coach','coach') THEN nullif(p_session->>'targetGroup','') ELSE NULL END;
BEGIN
  IF v_user_id IS NULL OR v_role NOT IN ('head_coach','coach','athlete') THEN RAISE EXCEPTION 'Action non autorisee.'; END IF;
  IF v_role='athlete' AND NOT (v_my_athlete_id=ANY(p_athlete_ids)) THEN RAISE EXCEPTION 'Ta propre affectation est obligatoire.'; END IF;
  IF p_idempotency_key IS NOT NULL THEN
    PERFORM pg_advisory_xact_lock(hashtextextended('create_session_with_athletes:'||p_idempotency_key,0));
    SELECT result INTO v_cached FROM public.rpc_idempotency
    WHERE fn_name='create_session_with_athletes' AND idempotency_key=p_idempotency_key AND actor_user_id=v_user_id;
    IF v_cached IS NOT NULL THEN RETURN v_cached; END IF;
  END IF;
  PERFORM public._assert_session_write(p_session,p_athlete_ids,NULL);
  INSERT INTO public.sessions(
    club_id,week,day,session_date,time,type,category,title,training_focus,
    description,instructions,duration_minutes,load_weight,pdf_url,created_by,
    source_kind,target_group
  ) VALUES (
    v_club_id,nullif(p_session->>'week','')::integer,nullif(p_session->>'day',''),
    (p_session->>'sessionDate')::date,p_session->>'time',nullif(p_session->>'type',''),
    nullif(p_session->>'category',''),btrim(p_session->>'title'),nullif(p_session->>'trainingFocus',''),
    nullif(p_session->>'description',''),nullif(p_session->>'instructions',''),
    (p_session->>'durationMinutes')::integer,coalesce(nullif(p_session->>'loadWeight','')::numeric,1.0),
    nullif(p_session->>'pdfUrl',''),v_user_id,
    CASE WHEN v_target_group IS NULL THEN 'individual' ELSE 'group' END,v_target_group
  ) RETURNING id INTO v_session_id;
  INSERT INTO public.session_athletes(session_id,athlete_id,status)
  SELECT v_session_id,athlete_id,NULL FROM unnest(p_athlete_ids) athlete_id;
  v_result:=jsonb_build_object('sessionId',v_session_id);
  IF p_idempotency_key IS NOT NULL THEN
    INSERT INTO public.rpc_idempotency(fn_name,idempotency_key,actor_user_id,result)
    VALUES('create_session_with_athletes',p_idempotency_key,v_user_id,v_result)
    ON CONFLICT(fn_name,idempotency_key) DO NOTHING;
  END IF;
  RETURN v_result;
END;
$$;

CREATE OR REPLACE FUNCTION public.update_session_with_athletes(
  p_session_id integer,
  p_session jsonb,
  p_athlete_ids integer[]
) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $$
DECLARE
  v_user_id integer:=public.get_my_user_id();
  v_club_id integer:=public.get_my_club_id();
  v_role text:=public.get_my_role();
  v_existing public.sessions%ROWTYPE;
  v_target_group text;
BEGIN
  SELECT * INTO v_existing FROM public.sessions WHERE id=p_session_id FOR UPDATE;
  IF NOT FOUND OR v_existing.club_id<>v_club_id THEN RAISE EXCEPTION 'Seance introuvable.'; END IF;
  IF v_role NOT IN ('head_coach','coach') AND NOT (v_role='athlete' AND v_existing.created_by=v_user_id) THEN RAISE EXCEPTION 'Action non autorisee.'; END IF;
  IF v_role='athlete' AND NOT (public.get_my_athlete_id()=ANY(p_athlete_ids)) THEN RAISE EXCEPTION 'Ta propre affectation est obligatoire.'; END IF;
  PERFORM public._assert_session_write(p_session,p_athlete_ids,p_session_id);
  v_target_group:=CASE WHEN v_role IN ('head_coach','coach') AND p_session?'targetGroup'
    THEN nullif(p_session->>'targetGroup','') ELSE v_existing.target_group END;
  UPDATE public.sessions SET
    week=nullif(p_session->>'week','')::integer,day=nullif(p_session->>'day',''),
    session_date=(p_session->>'sessionDate')::date,time=p_session->>'time',
    type=nullif(p_session->>'type',''),category=nullif(p_session->>'category',''),
    title=btrim(p_session->>'title'),training_focus=nullif(p_session->>'trainingFocus',''),
    description=nullif(p_session->>'description',''),instructions=nullif(p_session->>'instructions',''),
    duration_minutes=(p_session->>'durationMinutes')::integer,
    load_weight=coalesce(nullif(p_session->>'loadWeight','')::numeric,load_weight),
    pdf_url=CASE WHEN p_session?'pdfUrl' THEN nullif(p_session->>'pdfUrl','') ELSE pdf_url END,
    target_group=v_target_group,
    source_kind=CASE WHEN series_id IS NULL AND source_kind IN ('individual','group')
      THEN CASE WHEN v_target_group IS NULL THEN 'individual' ELSE 'group' END ELSE source_kind END,
    updated_by=CASE WHEN v_role IN ('head_coach','coach') THEN v_user_id ELSE updated_by END,
    updated_at=now()
  WHERE id=p_session_id;
  DELETE FROM public.session_athletes WHERE session_id=p_session_id AND NOT (athlete_id=ANY(p_athlete_ids));
  INSERT INTO public.session_athletes(session_id,athlete_id,status)
  SELECT p_session_id,athlete_id,NULL FROM unnest(p_athlete_ids) athlete_id ON CONFLICT(session_id,athlete_id) DO NOTHING;
  RETURN jsonb_build_object('sessionId',p_session_id);
END;
$$;

CREATE TABLE IF NOT EXISTS public.session_templates (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  club_id integer NOT NULL REFERENCES public.clubs(id) ON DELETE CASCADE,
  name text NOT NULL,
  category text,
  type text,
  training_focus text,
  title text NOT NULL,
  duration_minutes integer NOT NULL,
  description text,
  instructions text,
  created_by integer NOT NULL REFERENCES public.users(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (club_id, name),
  CONSTRAINT session_templates_duration_check CHECK (duration_minutes BETWEEN 1 AND 1440)
);

ALTER TABLE public.session_series ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.session_templates ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS session_series_club_read ON public.session_series;
CREATE POLICY session_series_club_read ON public.session_series
  FOR SELECT TO authenticated USING (club_id = public.get_my_club_id());
DROP POLICY IF EXISTS session_series_staff_manage ON public.session_series;
CREATE POLICY session_series_staff_manage ON public.session_series
  FOR ALL TO authenticated
  USING (club_id = public.get_my_club_id() AND public.get_my_role() IN ('head_coach', 'coach'))
  WITH CHECK (club_id = public.get_my_club_id() AND public.get_my_role() IN ('head_coach', 'coach'));

DROP POLICY IF EXISTS session_templates_club_read ON public.session_templates;
CREATE POLICY session_templates_club_read ON public.session_templates
  FOR SELECT TO authenticated USING (club_id = public.get_my_club_id());
DROP POLICY IF EXISTS session_templates_staff_manage ON public.session_templates;
CREATE POLICY session_templates_staff_manage ON public.session_templates
  FOR ALL TO authenticated
  USING (club_id = public.get_my_club_id() AND public.get_my_role() IN ('head_coach', 'coach'))
  WITH CHECK (club_id = public.get_my_club_id() AND public.get_my_role() IN ('head_coach', 'coach'));

GRANT SELECT, INSERT, UPDATE, DELETE ON public.session_series, public.session_templates TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;

CREATE OR REPLACE FUNCTION public._series_dates(
  p_starts_on date,
  p_ends_on date,
  p_occurrence_count integer,
  p_interval_weeks integer,
  p_weekdays smallint[]
) RETURNS TABLE(occurrence_date date)
LANGUAGE sql
IMMUTABLE
SET search_path TO 'public'
AS $$
  SELECT candidate::date
  FROM generate_series(
    p_starts_on::timestamp,
    coalesce(p_ends_on, p_starts_on + 730)::timestamp,
    interval '1 day'
  ) candidate
  WHERE extract(isodow FROM candidate)::smallint = ANY(p_weekdays)
    AND ((candidate::date - p_starts_on) / 7) % p_interval_weeks = 0
  ORDER BY candidate
  LIMIT coalesce(p_occurrence_count, 104)
$$;

CREATE OR REPLACE FUNCTION public.create_session_series_with_occurrences(
  p_series jsonb,
  p_athlete_ids integer[],
  p_idempotency_key text DEFAULT NULL
) RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_user_id integer := public.get_my_user_id();
  v_club_id integer := public.get_my_club_id();
  v_series_id bigint;
  v_date date;
  v_session_id integer;
  v_count integer := 0;
  v_weekdays smallint[];
  v_interval integer := coalesce(nullif(p_series->>'intervalWeeks', '')::integer, 1);
  v_starts_on date := nullif(p_series->>'startsOn', '')::date;
  v_ends_on date := nullif(p_series->>'endsOn', '')::date;
  v_occurrence_count integer := nullif(p_series->>'occurrenceCount', '')::integer;
  v_source text := CASE WHEN nullif(p_series->>'targetGroup', '') IS NULL THEN 'series' ELSE 'group_series' END;
  v_cached jsonb;
  v_result jsonb;
BEGIN
  IF v_user_id IS NULL OR public.get_my_role() NOT IN ('head_coach', 'coach') THEN
    RAISE EXCEPTION 'Action non autorisee.';
  END IF;
  IF p_idempotency_key IS NOT NULL THEN
    PERFORM pg_advisory_xact_lock(hashtextextended('create_session_series:' || p_idempotency_key, 0));
    SELECT result INTO v_cached FROM public.rpc_idempotency
    WHERE fn_name = 'create_session_series_with_occurrences'
      AND idempotency_key = p_idempotency_key AND actor_user_id = v_user_id;
    IF v_cached IS NOT NULL THEN RETURN v_cached; END IF;
  END IF;

  SELECT array_agg(DISTINCT value::smallint ORDER BY value::smallint)
  INTO v_weekdays
  FROM jsonb_array_elements_text(coalesce(p_series->'weekdays', '[]'::jsonb)) value;
  IF v_starts_on IS NULL OR cardinality(coalesce(v_weekdays, ARRAY[]::smallint[])) = 0 THEN
    RAISE EXCEPTION 'Date de debut et jour de recurrence requis.';
  END IF;
  IF v_ends_on IS NULL AND v_occurrence_count IS NULL THEN
    RAISE EXCEPTION 'Indique une date de fin ou un nombre de repetitions.';
  END IF;
  IF v_ends_on IS NOT NULL AND v_ends_on > v_starts_on + 730 THEN
    RAISE EXCEPTION 'Une serie ne peut pas depasser deux ans.';
  END IF;

  INSERT INTO public.session_series (
    club_id, title, time, type, category, training_focus, duration_minutes,
    description, instructions, interval_weeks, weekdays, starts_on, ends_on,
    occurrence_count, target_group, created_by
  ) VALUES (
    v_club_id, btrim(p_series->>'title'), p_series->>'time', nullif(p_series->>'type', ''),
    nullif(p_series->>'category', ''), nullif(p_series->>'trainingFocus', ''),
    (p_series->>'durationMinutes')::integer, nullif(p_series->>'description', ''),
    nullif(p_series->>'instructions', ''), v_interval, v_weekdays, v_starts_on,
    v_ends_on, v_occurrence_count, nullif(p_series->>'targetGroup', ''), v_user_id
  ) RETURNING id INTO v_series_id;

  FOR v_date IN SELECT occurrence_date FROM public._series_dates(
    v_starts_on, v_ends_on, v_occurrence_count, v_interval, v_weekdays
  ) LOOP
    PERFORM public._assert_session_write(
      jsonb_build_object(
        'title', p_series->>'title', 'sessionDate', v_date, 'time', p_series->>'time',
        'durationMinutes', p_series->>'durationMinutes'
      ), p_athlete_ids, NULL
    );
    INSERT INTO public.sessions (
      club_id, week, day, session_date, time, type, category, title,
      training_focus, description, instructions, duration_minutes, load_weight,
      created_by, series_id, series_original_date, source_kind, target_group
    ) VALUES (
      v_club_id, extract(week FROM v_date)::integer,
      CASE extract(isodow FROM v_date)::integer
        WHEN 1 THEN 'Lundi' WHEN 2 THEN 'Mardi' WHEN 3 THEN 'Mercredi'
        WHEN 4 THEN 'Jeudi' WHEN 5 THEN 'Vendredi' WHEN 6 THEN 'Samedi' ELSE 'Dimanche' END,
      v_date, p_series->>'time', nullif(p_series->>'type', ''), nullif(p_series->>'category', ''),
      btrim(p_series->>'title'), nullif(p_series->>'trainingFocus', ''),
      nullif(p_series->>'description', ''), nullif(p_series->>'instructions', ''),
      (p_series->>'durationMinutes')::integer,
      coalesce(nullif(p_series->>'loadWeight', '')::numeric, 1.0), v_user_id,
      v_series_id, v_date, v_source, nullif(p_series->>'targetGroup', '')
    ) RETURNING id INTO v_session_id;

    INSERT INTO public.session_athletes (session_id, athlete_id, status)
    SELECT v_session_id, athlete_id, NULL FROM unnest(p_athlete_ids) athlete_id;
    v_count := v_count + 1;
  END LOOP;

  IF v_count = 0 THEN RAISE EXCEPTION 'Aucune occurrence generee.'; END IF;
  v_result := jsonb_build_object('seriesId', v_series_id, 'occurrenceCount', v_count);
  IF p_idempotency_key IS NOT NULL THEN
    INSERT INTO public.rpc_idempotency (fn_name, idempotency_key, actor_user_id, result)
    VALUES ('create_session_series_with_occurrences', p_idempotency_key, v_user_id, v_result)
    ON CONFLICT (fn_name, idempotency_key) DO NOTHING;
  END IF;
  RETURN v_result;
END;
$$;

CREATE OR REPLACE FUNCTION public.update_recurring_session(
  p_session_id integer,
  p_scope text,
  p_patch jsonb,
  p_athlete_ids integer[]
) RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_origin public.sessions%ROWTYPE;
  v_target public.sessions%ROWTYPE;
  v_form jsonb;
  v_count integer := 0;
BEGIN
  IF p_scope NOT IN ('single', 'future', 'all') THEN RAISE EXCEPTION 'Portee invalide.'; END IF;
  SELECT * INTO v_origin FROM public.sessions WHERE id = p_session_id;
  IF NOT FOUND OR v_origin.club_id <> public.get_my_club_id() THEN RAISE EXCEPTION 'Seance introuvable.'; END IF;
  IF public.get_my_role() NOT IN ('head_coach', 'coach') THEN RAISE EXCEPTION 'Action non autorisee.'; END IF;

  FOR v_target IN
    SELECT session.* FROM public.sessions session
    WHERE session.club_id = v_origin.club_id
      AND (
        (p_scope = 'single' AND session.id = v_origin.id)
        OR (p_scope = 'future' AND session.series_id = v_origin.series_id AND session.session_date >= v_origin.session_date)
        OR (p_scope = 'all' AND session.series_id = v_origin.series_id AND session.session_date >= current_date)
      )
    ORDER BY session.session_date
  LOOP
    v_form := jsonb_build_object(
      'title', v_target.title, 'type', v_target.type, 'category', v_target.category,
      'trainingFocus', v_target.training_focus, 'sessionDate', v_target.session_date,
      'time', v_target.time, 'durationMinutes', v_target.duration_minutes,
      'description', v_target.description, 'instructions', v_target.instructions,
      'loadWeight', v_target.load_weight, 'pdfUrl', v_target.pdf_url,
      'week', v_target.week, 'day', v_target.day
    ) || CASE
      WHEN p_scope = 'single' THEN p_patch
      ELSE p_patch - ARRAY['sessionDate','week','day']
    END;
    PERFORM public.update_session_with_athletes(v_target.id, v_form, p_athlete_ids);
    UPDATE public.sessions SET updated_at = now(), updated_by = public.get_my_user_id(),
      source_kind = CASE WHEN p_scope = 'single' THEN 'exception' ELSE source_kind END
    WHERE id = v_target.id;
    v_count := v_count + 1;
  END LOOP;

  IF v_origin.series_id IS NOT NULL AND p_scope <> 'single' THEN
    UPDATE public.session_series SET
      title = coalesce(nullif(p_patch->>'title', ''), title),
      time = coalesce(nullif(p_patch->>'time', ''), time),
      type = CASE WHEN p_patch ? 'type' THEN nullif(p_patch->>'type', '') ELSE type END,
      category = CASE WHEN p_patch ? 'category' THEN nullif(p_patch->>'category', '') ELSE category END,
      training_focus = CASE WHEN p_patch ? 'trainingFocus' THEN nullif(p_patch->>'trainingFocus', '') ELSE training_focus END,
      duration_minutes = coalesce(nullif(p_patch->>'durationMinutes', '')::integer, duration_minutes),
      description = CASE WHEN p_patch ? 'description' THEN nullif(p_patch->>'description', '') ELSE description END,
      instructions = CASE WHEN p_patch ? 'instructions' THEN nullif(p_patch->>'instructions', '') ELSE instructions END,
      updated_at = now(), updated_by = public.get_my_user_id()
    WHERE id = v_origin.series_id;
  END IF;
  RETURN jsonb_build_object('updatedCount', v_count, 'scope', p_scope);
END;
$$;

CREATE OR REPLACE FUNCTION public.delete_recurring_session(p_session_id integer, p_scope text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_origin public.sessions%ROWTYPE;
  v_deleted integer := 0;
  v_preserved integer := 0;
BEGIN
  IF p_scope NOT IN ('single', 'future', 'all') THEN RAISE EXCEPTION 'Portee invalide.'; END IF;
  SELECT * INTO v_origin FROM public.sessions WHERE id = p_session_id FOR UPDATE;
  IF NOT FOUND OR v_origin.club_id <> public.get_my_club_id() THEN RAISE EXCEPTION 'Seance introuvable.'; END IF;
  IF public.get_my_role() NOT IN ('head_coach', 'coach') THEN RAISE EXCEPTION 'Action non autorisee.'; END IF;

  IF p_scope = 'single' OR v_origin.series_id IS NULL THEN
    PERFORM public.delete_session_transactional(p_session_id);
    RETURN jsonb_build_object('deletedCount', 1, 'preservedCount', 0, 'scope', 'single');
  END IF;

  SELECT count(*) INTO v_preserved FROM public.sessions session
  WHERE session.series_id = v_origin.series_id
    AND session.session_date < CASE WHEN p_scope = 'future' THEN v_origin.session_date ELSE current_date END;

  DELETE FROM public.sessions session
  WHERE session.series_id = v_origin.series_id
    AND session.session_date >= CASE WHEN p_scope = 'future' THEN v_origin.session_date ELSE current_date END
    AND NOT EXISTS (
      SELECT 1 FROM public.session_athletes assignment
      WHERE assignment.session_id = session.id
        AND (assignment.rpe IS NOT NULL OR assignment.comment IS NOT NULL OR assignment.feedback_submitted_at IS NOT NULL)
    );
  GET DIAGNOSTICS v_deleted = ROW_COUNT;

  SELECT v_preserved + count(*) INTO v_preserved FROM public.sessions session
  WHERE session.series_id = v_origin.series_id
    AND session.session_date >= CASE WHEN p_scope = 'future' THEN v_origin.session_date ELSE current_date END;
  RETURN jsonb_build_object('deletedCount', v_deleted, 'preservedCount', v_preserved, 'scope', p_scope);
END;
$$;

CREATE OR REPLACE FUNCTION public.duplicate_session_transactional(
  p_session_id integer,
  p_session_date date,
  p_athlete_ids integer[] DEFAULT NULL
) RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_source public.sessions%ROWTYPE;
  v_new_id integer;
  v_targets integer[];
BEGIN
  SELECT * INTO v_source FROM public.sessions WHERE id = p_session_id;
  IF NOT FOUND OR v_source.club_id <> public.get_my_club_id() THEN RAISE EXCEPTION 'Seance introuvable.'; END IF;
  IF public.get_my_role() NOT IN ('head_coach', 'coach') THEN RAISE EXCEPTION 'Action non autorisee.'; END IF;
  SELECT coalesce(p_athlete_ids, array_agg(athlete_id ORDER BY athlete_id)) INTO v_targets
  FROM public.session_athletes WHERE session_id = p_session_id;
  PERFORM public._assert_session_write(jsonb_build_object(
    'title', v_source.title, 'sessionDate', p_session_date, 'time', v_source.time,
    'durationMinutes', v_source.duration_minutes
  ), v_targets, NULL);

  INSERT INTO public.sessions (
    club_id, title, day, time, type, category, description, instructions, week,
    load_weight, pdf_url, duration_minutes, created_by, session_date,
    training_focus, source_kind, target_group, parent_session_id
  ) VALUES (
    v_source.club_id, v_source.title,
    CASE extract(isodow FROM p_session_date)::integer
      WHEN 1 THEN 'Lundi' WHEN 2 THEN 'Mardi' WHEN 3 THEN 'Mercredi'
      WHEN 4 THEN 'Jeudi' WHEN 5 THEN 'Vendredi' WHEN 6 THEN 'Samedi' ELSE 'Dimanche' END,
    v_source.time, v_source.type, v_source.category, v_source.description,
    v_source.instructions, extract(week FROM p_session_date)::integer,
    v_source.load_weight, v_source.pdf_url, v_source.duration_minutes,
    public.get_my_user_id(), p_session_date, v_source.training_focus,
    'duplicate', v_source.target_group, v_source.id
  ) RETURNING id INTO v_new_id;
  INSERT INTO public.session_athletes (session_id, athlete_id, status)
  SELECT v_new_id, athlete_id, NULL FROM unnest(v_targets) athlete_id;
  RETURN jsonb_build_object('sessionId', v_new_id, 'sourceSessionId', p_session_id);
END;
$$;

CREATE OR REPLACE FUNCTION public.duplicate_week_transactional(
  p_source_monday date,
  p_target_monday date,
  p_athlete_ids integer[] DEFAULT NULL
) RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_source record;
  v_result jsonb;
  v_ids integer[] := ARRAY[]::integer[];
BEGIN
  IF public.get_my_role() NOT IN ('head_coach', 'coach') THEN RAISE EXCEPTION 'Action non autorisee.'; END IF;
  IF extract(isodow FROM p_source_monday) <> 1 OR extract(isodow FROM p_target_monday) <> 1 THEN
    RAISE EXCEPTION 'Les dates doivent etre des lundis.';
  END IF;
  FOR v_source IN
    SELECT id, session_date FROM public.sessions
    WHERE club_id = public.get_my_club_id()
      AND session_date BETWEEN p_source_monday AND p_source_monday + 6
      AND (p_athlete_ids IS NULL OR EXISTS (
        SELECT 1 FROM public.session_athletes assignment
        WHERE assignment.session_id = sessions.id AND assignment.athlete_id = ANY(p_athlete_ids)
      ))
    ORDER BY session_date, time
  LOOP
    v_result := public.duplicate_session_transactional(
      v_source.id, p_target_monday + (v_source.session_date - p_source_monday), p_athlete_ids
    );
    v_ids := array_append(v_ids, (v_result->>'sessionId')::integer);
  END LOOP;
  RETURN jsonb_build_object('sessionIds', to_jsonb(v_ids), 'duplicatedCount', cardinality(v_ids));
END;
$$;

CREATE OR REPLACE FUNCTION public.save_session_template(p_name text, p_session_id integer)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE v_id bigint;
BEGIN
  IF public.get_my_role() NOT IN ('head_coach', 'coach') THEN RAISE EXCEPTION 'Action non autorisee.'; END IF;
  INSERT INTO public.session_templates (
    club_id, name, category, type, training_focus, title, duration_minutes,
    description, instructions, created_by
  )
  SELECT club_id, btrim(p_name), category, type, training_focus, title,
    duration_minutes, description, instructions, public.get_my_user_id()
  FROM public.sessions
  WHERE id = p_session_id AND club_id = public.get_my_club_id()
  ON CONFLICT (club_id, name) DO UPDATE SET
    category = EXCLUDED.category, type = EXCLUDED.type,
    training_focus = EXCLUDED.training_focus, title = EXCLUDED.title,
    duration_minutes = EXCLUDED.duration_minutes, description = EXCLUDED.description,
    instructions = EXCLUDED.instructions, updated_at = now()
  RETURNING id INTO v_id;
  IF v_id IS NULL THEN RAISE EXCEPTION 'Seance introuvable.'; END IF;
  RETURN v_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.create_session_from_template(
  p_template_id bigint,
  p_schedule jsonb,
  p_athlete_ids integer[],
  p_idempotency_key text DEFAULT NULL
) RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE v_template public.session_templates%ROWTYPE; v_result jsonb;
BEGIN
  SELECT * INTO v_template FROM public.session_templates
  WHERE id = p_template_id AND club_id = public.get_my_club_id();
  IF NOT FOUND THEN RAISE EXCEPTION 'Modele introuvable.'; END IF;
  v_result := public.create_session_with_athletes(
    jsonb_build_object(
      'title', v_template.title, 'category', v_template.category, 'type', v_template.type,
      'trainingFocus', v_template.training_focus, 'durationMinutes', v_template.duration_minutes,
      'description', v_template.description, 'instructions', v_template.instructions
    ) || p_schedule,
    p_athlete_ids, p_idempotency_key
  );
  UPDATE public.sessions SET source_kind = 'template' WHERE id = (v_result->>'sessionId')::integer;
  RETURN v_result;
END;
$$;

CREATE OR REPLACE FUNCTION public.refresh_series_group_members(p_series_id bigint, p_from_date date DEFAULT current_date)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE v_series public.session_series%ROWTYPE; v_count integer;
BEGIN
  SELECT * INTO v_series FROM public.session_series WHERE id = p_series_id FOR UPDATE;
  IF NOT FOUND OR v_series.club_id <> public.get_my_club_id() OR v_series.target_group IS NULL THEN
    RAISE EXCEPTION 'Serie de groupe introuvable.';
  END IF;
  IF public.get_my_role() NOT IN ('head_coach', 'coach') THEN RAISE EXCEPTION 'Action non autorisee.'; END IF;
  DELETE FROM public.session_athletes assignment
  USING public.sessions session
  WHERE assignment.session_id = session.id AND session.series_id = p_series_id
    AND session.session_date >= p_from_date
    AND assignment.feedback_submitted_at IS NULL AND assignment.rpe IS NULL AND assignment.comment IS NULL;
  INSERT INTO public.session_athletes (session_id, athlete_id, status)
  SELECT session.id, athlete.id, NULL
  FROM public.sessions session
  JOIN public.athletes athlete ON athlete.club_id = v_series.club_id
    AND athlete.group_name = v_series.target_group
  WHERE session.series_id = p_series_id AND session.session_date >= p_from_date
  ON CONFLICT (session_id, athlete_id) DO NOTHING;
  GET DIAGNOSTICS v_count = ROW_COUNT;
  RETURN jsonb_build_object('seriesId', p_series_id, 'addedAssignments', v_count, 'fromDate', p_from_date);
END;
$$;

-- ---------------------------------------------------------------------------
-- Stages/tests/autres : événements sportifs distincts des catégories de charge
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.planning_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  club_id integer NOT NULL REFERENCES public.clubs(id) ON DELETE CASCADE,
  kind text NOT NULL,
  name text NOT NULL,
  starts_on date NOT NULL,
  ends_on date NOT NULL,
  time text,
  location text,
  description text,
  notes text,
  custom_label text,
  target_group text,
  created_by integer NOT NULL REFERENCES public.users(id),
  updated_by integer REFERENCES public.users(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT planning_events_kind_check CHECK (kind IN ('stage', 'test', 'rest', 'custom')),
  CONSTRAINT planning_events_dates_check CHECK (ends_on >= starts_on),
  CONSTRAINT planning_events_time_check CHECK (time IS NULL OR time ~ '^(?:[01][0-9]|2[0-3]):[0-5][0-9]$')
);
CREATE TABLE IF NOT EXISTS public.planning_event_athletes (
  event_id bigint NOT NULL REFERENCES public.planning_events(id) ON DELETE CASCADE,
  athlete_id integer NOT NULL REFERENCES public.athletes(id) ON DELETE CASCADE,
  PRIMARY KEY (event_id, athlete_id)
);
ALTER TABLE public.sessions
  ADD COLUMN IF NOT EXISTS planning_event_id bigint REFERENCES public.planning_events(id) ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS planning_events_club_dates_idx ON public.planning_events (club_id, starts_on, ends_on);
CREATE INDEX IF NOT EXISTS planning_event_athletes_athlete_idx ON public.planning_event_athletes (athlete_id, event_id);

CREATE OR REPLACE FUNCTION public.can_view_planning_event(p_event_id bigint)
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public' AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.planning_events event
    WHERE event.id=p_event_id AND event.club_id=public.get_my_club_id()
      AND (public.get_my_role() IN ('head_coach','coach') OR EXISTS (
        SELECT 1 FROM public.planning_event_athletes assignment
        WHERE assignment.event_id=event.id AND assignment.athlete_id=public.get_my_athlete_id()
      ))
  )
$$;

CREATE OR REPLACE FUNCTION public.can_manage_planning_event(p_event_id bigint)
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public' AS $$
  SELECT public.get_my_role() IN ('head_coach','coach') AND EXISTS (
    SELECT 1 FROM public.planning_events event
    WHERE event.id=p_event_id AND event.club_id=public.get_my_club_id()
  )
$$;

ALTER TABLE public.planning_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.planning_event_athletes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS planning_events_visible ON public.planning_events;
CREATE POLICY planning_events_visible ON public.planning_events FOR SELECT TO authenticated
  USING (public.can_view_planning_event(id));
DROP POLICY IF EXISTS planning_events_staff_manage ON public.planning_events;
CREATE POLICY planning_events_staff_manage ON public.planning_events FOR ALL TO authenticated
  USING (club_id = public.get_my_club_id() AND public.get_my_role() IN ('head_coach', 'coach'))
  WITH CHECK (club_id = public.get_my_club_id() AND public.get_my_role() IN ('head_coach', 'coach'));
DROP POLICY IF EXISTS planning_event_athletes_visible ON public.planning_event_athletes;
CREATE POLICY planning_event_athletes_visible ON public.planning_event_athletes FOR SELECT TO authenticated
  USING (public.can_view_planning_event(event_id));
DROP POLICY IF EXISTS planning_event_athletes_staff_manage ON public.planning_event_athletes;
CREATE POLICY planning_event_athletes_staff_manage ON public.planning_event_athletes FOR ALL TO authenticated
  USING (public.can_manage_planning_event(event_id))
  WITH CHECK (
    public.can_manage_planning_event(event_id)
    AND EXISTS (SELECT 1 FROM public.athletes athlete WHERE athlete.id = planning_event_athletes.athlete_id AND athlete.club_id = public.get_my_club_id())
  );
GRANT SELECT, INSERT, UPDATE, DELETE ON public.planning_events, public.planning_event_athletes TO authenticated;

CREATE OR REPLACE FUNCTION public.upsert_planning_event_with_athletes(
  p_event_id bigint,
  p_event jsonb,
  p_athlete_ids integer[]
) RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE v_event_id bigint := p_event_id; v_club_id integer := public.get_my_club_id();
BEGIN
  IF public.get_my_role() NOT IN ('head_coach', 'coach') THEN RAISE EXCEPTION 'Action non autorisee.'; END IF;
  IF cardinality(coalesce(p_athlete_ids, ARRAY[]::integer[])) = 0 THEN RAISE EXCEPTION 'Selectionne au moins un athlete.'; END IF;
  IF EXISTS (SELECT 1 FROM unnest(p_athlete_ids) athlete_id WHERE NOT EXISTS (
    SELECT 1 FROM public.athletes athlete WHERE athlete.id = athlete_id AND athlete.club_id = v_club_id
  )) THEN RAISE EXCEPTION 'Un athlete selectionne n appartient pas au club.'; END IF;

  IF v_event_id IS NULL THEN
    INSERT INTO public.planning_events (club_id, kind, name, starts_on, ends_on, time, location, description, notes, custom_label, target_group, created_by)
    VALUES (v_club_id, p_event->>'kind', btrim(p_event->>'name'), (p_event->>'startsOn')::date,
      coalesce(nullif(p_event->>'endsOn','')::date, (p_event->>'startsOn')::date), nullif(p_event->>'time',''),
      nullif(p_event->>'location',''), nullif(p_event->>'description',''), nullif(p_event->>'notes',''),
      nullif(p_event->>'customLabel',''), nullif(p_event->>'targetGroup',''), public.get_my_user_id())
    RETURNING id INTO v_event_id;
  ELSE
    UPDATE public.planning_events SET kind = p_event->>'kind', name = btrim(p_event->>'name'),
      starts_on = (p_event->>'startsOn')::date,
      ends_on = coalesce(nullif(p_event->>'endsOn','')::date, (p_event->>'startsOn')::date),
      time = nullif(p_event->>'time',''), location = nullif(p_event->>'location',''),
      description = nullif(p_event->>'description',''), notes = nullif(p_event->>'notes',''),
      custom_label = nullif(p_event->>'customLabel',''), target_group = nullif(p_event->>'targetGroup',''),
      updated_by = public.get_my_user_id(), updated_at = now()
    WHERE id = v_event_id AND club_id = v_club_id;
    IF NOT FOUND THEN RAISE EXCEPTION 'Evenement introuvable.'; END IF;
  END IF;
  DELETE FROM public.planning_event_athletes WHERE event_id = v_event_id AND NOT (athlete_id = ANY(p_athlete_ids));
  INSERT INTO public.planning_event_athletes (event_id, athlete_id)
  SELECT v_event_id, athlete_id FROM unnest(p_athlete_ids) athlete_id
  ON CONFLICT (event_id, athlete_id) DO NOTHING;
  RETURN jsonb_build_object('eventId', v_event_id);
END;
$$;

CREATE OR REPLACE FUNCTION public.delete_planning_event(p_event_id bigint)
RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $$
BEGIN
  IF public.get_my_role() NOT IN ('head_coach', 'coach') THEN RAISE EXCEPTION 'Action non autorisee.'; END IF;
  DELETE FROM public.planning_events WHERE id = p_event_id AND club_id = public.get_my_club_id();
  IF NOT FOUND THEN RAISE EXCEPTION 'Evenement introuvable.'; END IF;
  RETURN p_event_id;
END;
$$;

-- ---------------------------------------------------------------------------
-- CRUD compétitions complet, sans nouvelle source de vérité
-- ---------------------------------------------------------------------------
ALTER TABLE public.competitions ADD COLUMN IF NOT EXISTS notes text;

CREATE OR REPLACE FUNCTION public.update_competition_with_athletes(
  p_competition_id integer,
  p_name text,
  p_date date,
  p_location text,
  p_type text,
  p_notes text,
  p_athlete_entries jsonb
) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $$
DECLARE v_club_id integer := public.get_my_club_id();
BEGIN
  IF public.get_my_role() NOT IN ('head_coach','coach') THEN RAISE EXCEPTION 'Action non autorisee.'; END IF;
  IF nullif(btrim(p_name),'') IS NULL OR p_date IS NULL THEN RAISE EXCEPTION 'Nom et date requis.'; END IF;
  IF EXISTS (
    SELECT 1 FROM jsonb_to_recordset(coalesce(p_athlete_entries,'[]'::jsonb)) AS entry("athleteId" integer, "plannedEvent" text)
    WHERE NOT EXISTS (SELECT 1 FROM public.athletes athlete WHERE athlete.id = entry."athleteId" AND athlete.club_id = v_club_id)
  ) THEN RAISE EXCEPTION 'Un athlete selectionne n appartient pas au club.'; END IF;
  UPDATE public.competitions SET name=btrim(p_name), date=p_date, location=nullif(p_location,''), type=nullif(p_type,''), notes=nullif(p_notes,'')
  WHERE id=p_competition_id AND club_id=v_club_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'Competition introuvable.'; END IF;
  DELETE FROM public.competition_athletes WHERE competition_id=p_competition_id AND athlete_id NOT IN (
    SELECT entry."athleteId" FROM jsonb_to_recordset(coalesce(p_athlete_entries,'[]'::jsonb)) AS entry("athleteId" integer, "plannedEvent" text)
  );
  INSERT INTO public.competition_athletes (competition_id, athlete_id, planned_event)
  SELECT p_competition_id, entry."athleteId", nullif(entry."plannedEvent",'')
  FROM jsonb_to_recordset(coalesce(p_athlete_entries,'[]'::jsonb)) AS entry("athleteId" integer, "plannedEvent" text)
  ON CONFLICT (competition_id, athlete_id) DO UPDATE SET planned_event=EXCLUDED.planned_event;
  RETURN jsonb_build_object('competitionId',p_competition_id);
END;
$$;

CREATE OR REPLACE FUNCTION public.delete_competition_transactional(p_competition_id integer)
RETURNS integer LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $$
BEGIN
  IF public.get_my_role() NOT IN ('head_coach','coach') THEN RAISE EXCEPTION 'Action non autorisee.'; END IF;
  DELETE FROM public.competitions WHERE id=p_competition_id AND club_id=public.get_my_club_id();
  IF NOT FOUND THEN RAISE EXCEPTION 'Competition introuvable ou liee a des resultats conserves.'; END IF;
  RETURN p_competition_id;
END;
$$;

REVOKE ALL ON FUNCTION public._series_dates(date,date,integer,integer,smallint[]) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.can_view_planning_event(bigint) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.can_manage_planning_event(bigint) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.create_session_series_with_occurrences(jsonb,integer[],text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.update_recurring_session(integer,text,jsonb,integer[]) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.delete_recurring_session(integer,text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.duplicate_session_transactional(integer,date,integer[]) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.duplicate_week_transactional(date,date,integer[]) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.save_session_template(text,integer) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.create_session_from_template(bigint,jsonb,integer[],text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.refresh_series_group_members(bigint,date) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.upsert_planning_event_with_athletes(bigint,jsonb,integer[]) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.delete_planning_event(bigint) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.update_competition_with_athletes(integer,text,date,text,text,text,jsonb) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.delete_competition_transactional(integer) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.create_session_series_with_occurrences(jsonb,integer[],text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.can_view_planning_event(bigint) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.can_manage_planning_event(bigint) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.update_recurring_session(integer,text,jsonb,integer[]) TO authenticated;
GRANT EXECUTE ON FUNCTION public.delete_recurring_session(integer,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.duplicate_session_transactional(integer,date,integer[]) TO authenticated;
GRANT EXECUTE ON FUNCTION public.duplicate_week_transactional(date,date,integer[]) TO authenticated;
GRANT EXECUTE ON FUNCTION public.save_session_template(text,integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_session_from_template(bigint,jsonb,integer[],text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.refresh_series_group_members(bigint,date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.upsert_planning_event_with_athletes(bigint,jsonb,integer[]) TO authenticated;
GRANT EXECUTE ON FUNCTION public.delete_planning_event(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_competition_with_athletes(integer,text,date,text,text,text,jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.delete_competition_transactional(integer) TO authenticated;

COMMIT;
