-- AthleteOS — configurable capabilities per club and per athlete.
-- Additive migration: existing operational data is never modified or deleted.

BEGIN;

ALTER TABLE public.clubs
  ADD COLUMN IF NOT EXISTS modules_configured_at timestamptz;

CREATE TABLE IF NOT EXISTS public.club_modules (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  club_id integer NOT NULL REFERENCES public.clubs(id) ON DELETE CASCADE,
  module_key text NOT NULL,
  enabled boolean NOT NULL DEFAULT true,
  config jsonb NOT NULL DEFAULT '{}'::jsonb,
  updated_by integer REFERENCES public.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT club_modules_key_check CHECK (module_key = ANY (ARRAY[
    'planning', 'performances', 'session_feedback', 'wellness',
    'training_load', 'health', 'messaging', 'social', 'reports'
  ]::text[])),
  CONSTRAINT club_modules_unique UNIQUE (club_id, module_key)
);

CREATE TABLE IF NOT EXISTS public.athlete_modules (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  athlete_id integer NOT NULL REFERENCES public.athletes(id) ON DELETE CASCADE,
  club_id integer NOT NULL REFERENCES public.clubs(id) ON DELETE CASCADE,
  module_key text NOT NULL,
  enabled boolean NOT NULL DEFAULT true,
  config jsonb NOT NULL DEFAULT '{}'::jsonb,
  updated_by integer REFERENCES public.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT athlete_modules_key_check CHECK (module_key = ANY (ARRAY[
    'planning', 'performances', 'session_feedback', 'wellness',
    'training_load', 'health', 'messaging', 'social', 'reports'
  ]::text[])),
  CONSTRAINT athlete_modules_unique UNIQUE (athlete_id, module_key)
);

CREATE INDEX IF NOT EXISTS club_modules_club_enabled_idx
  ON public.club_modules (club_id, enabled, module_key);
CREATE INDEX IF NOT EXISTS athlete_modules_club_athlete_idx
  ON public.athlete_modules (club_id, athlete_id, enabled);

CREATE OR REPLACE FUNCTION public.touch_module_updated_at()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public, pg_temp
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS club_modules_touch_updated_at ON public.club_modules;
CREATE TRIGGER club_modules_touch_updated_at
BEFORE UPDATE ON public.club_modules
FOR EACH ROW EXECUTE FUNCTION public.touch_module_updated_at();

DROP TRIGGER IF EXISTS athlete_modules_touch_updated_at ON public.athlete_modules;
CREATE TRIGGER athlete_modules_touch_updated_at
BEFORE UPDATE ON public.athlete_modules
FOR EACH ROW EXECUTE FUNCTION public.touch_module_updated_at();

CREATE OR REPLACE FUNCTION public.seed_club_modules()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  INSERT INTO public.club_modules (club_id, module_key, enabled)
  SELECT NEW.id, key, true
  FROM unnest(ARRAY[
    'planning', 'performances', 'session_feedback', 'wellness',
    'training_load', 'health', 'messaging', 'social', 'reports'
  ]::text[]) AS key
  ON CONFLICT (club_id, module_key) DO NOTHING;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS clubs_seed_modules ON public.clubs;
CREATE TRIGGER clubs_seed_modules
AFTER INSERT ON public.clubs
FOR EACH ROW EXECUTE FUNCTION public.seed_club_modules();

CREATE OR REPLACE FUNCTION public.seed_athlete_modules()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  INSERT INTO public.athlete_modules (athlete_id, club_id, module_key, enabled)
  SELECT NEW.id, NEW.club_id, key, true
  FROM unnest(ARRAY[
    'planning', 'performances', 'session_feedback', 'wellness',
    'training_load', 'health', 'messaging', 'social', 'reports'
  ]::text[]) AS key
  ON CONFLICT (athlete_id, module_key) DO NOTHING;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS athletes_seed_modules ON public.athletes;
CREATE TRIGGER athletes_seed_modules
AFTER INSERT ON public.athletes
FOR EACH ROW EXECUTE FUNCTION public.seed_athlete_modules();

-- Compatibility backfill: every existing capability remains available.
INSERT INTO public.club_modules (club_id, module_key, enabled)
SELECT c.id, key, true
FROM public.clubs c
CROSS JOIN unnest(ARRAY[
  'planning', 'performances', 'session_feedback', 'wellness',
  'training_load', 'health', 'messaging', 'social', 'reports'
]::text[]) AS key
ON CONFLICT (club_id, module_key) DO NOTHING;

INSERT INTO public.athlete_modules (athlete_id, club_id, module_key, enabled)
SELECT a.id, a.club_id, key, true
FROM public.athletes a
CROSS JOIN unnest(ARRAY[
  'planning', 'performances', 'session_feedback', 'wellness',
  'training_load', 'health', 'messaging', 'social', 'reports'
]::text[]) AS key
ON CONFLICT (athlete_id, module_key) DO NOTHING;

CREATE OR REPLACE FUNCTION public.is_club_module_enabled(p_club_id integer, p_module_key text)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT COALESCE(
    (SELECT cm.enabled FROM public.club_modules cm
     WHERE cm.club_id = p_club_id AND cm.module_key = p_module_key),
    true
  );
$$;

CREATE OR REPLACE FUNCTION public.is_athlete_module_enabled(p_athlete_id integer, p_module_key text)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT COALESCE(
    (SELECT public.is_club_module_enabled(a.club_id, p_module_key)
            AND COALESCE(am.enabled, true)
       FROM public.athletes a
       LEFT JOIN public.athlete_modules am
         ON am.athlete_id = a.id AND am.module_key = p_module_key
      WHERE a.id = p_athlete_id),
    false
  );
$$;

REVOKE ALL ON FUNCTION public.is_club_module_enabled(integer, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.is_athlete_module_enabled(integer, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.is_club_module_enabled(integer, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.is_athlete_module_enabled(integer, text) TO service_role;

ALTER TABLE public.club_modules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.athlete_modules ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS club_modules_read_same_club ON public.club_modules;
CREATE POLICY club_modules_read_same_club ON public.club_modules
FOR SELECT TO authenticated
USING (club_id = public.get_my_club_id());

DROP POLICY IF EXISTS athlete_modules_read_same_club_or_self ON public.athlete_modules;
CREATE POLICY athlete_modules_read_same_club_or_self ON public.athlete_modules
FOR SELECT TO authenticated
USING (
  club_id = public.get_my_club_id()
  AND (
    public.get_my_role() IN ('coach', 'head_coach')
    OR athlete_id = public.get_my_athlete_id()
  )
);

REVOKE INSERT, UPDATE, DELETE ON public.club_modules FROM authenticated;
REVOKE INSERT, UPDATE, DELETE ON public.athlete_modules FROM authenticated;
GRANT SELECT ON public.club_modules, public.athlete_modules TO authenticated;
GRANT ALL ON public.club_modules, public.athlete_modules TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.club_modules_id_seq TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.athlete_modules_id_seq TO service_role;

CREATE OR REPLACE FUNCTION public.configure_my_club_modules(p_enabled_module_keys text[])
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_club_id integer := public.get_my_club_id();
  v_user_id integer := public.get_my_user_id();
  v_allowed constant text[] := ARRAY[
    'planning', 'performances', 'session_feedback', 'wellness',
    'training_load', 'health', 'messaging', 'social', 'reports'
  ]::text[];
  v_enabled text[] := COALESCE(p_enabled_module_keys, ARRAY[]::text[]);
BEGIN
  IF v_club_id IS NULL OR public.get_my_role() <> 'head_coach' THEN
    RAISE EXCEPTION 'Action réservée au head coach.' USING ERRCODE = '42501';
  END IF;
  IF EXISTS (SELECT 1 FROM unnest(v_enabled) key WHERE NOT key = ANY(v_allowed)) THEN
    RAISE EXCEPTION 'Module inconnu.' USING ERRCODE = '22023';
  END IF;
  IF 'training_load' = ANY(v_enabled) AND NOT ('session_feedback' = ANY(v_enabled)) THEN
    RAISE EXCEPTION 'La charge nécessite le feedback de séance.' USING ERRCODE = '23514';
  END IF;

  INSERT INTO public.club_modules (club_id, module_key, enabled, updated_by)
  SELECT v_club_id, key, key = ANY(v_enabled), v_user_id FROM unnest(v_allowed) key
  ON CONFLICT (club_id, module_key) DO UPDATE
    SET enabled = EXCLUDED.enabled, updated_by = EXCLUDED.updated_by;

  UPDATE public.clubs SET modules_configured_at = now() WHERE id = v_club_id;
  RETURN jsonb_build_object('clubId', v_club_id, 'enabledModuleKeys', to_jsonb(v_enabled));
END;
$$;

CREATE OR REPLACE FUNCTION public.configure_athlete_modules(
  p_athlete_ids integer[],
  p_enabled_module_keys text[]
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_club_id integer := public.get_my_club_id();
  v_user_id integer := public.get_my_user_id();
  v_role text := public.get_my_role();
  v_ids integer[] := ARRAY(SELECT DISTINCT x FROM unnest(COALESCE(p_athlete_ids, ARRAY[]::integer[])) x);
  v_allowed constant text[] := ARRAY[
    'planning', 'performances', 'session_feedback', 'wellness',
    'training_load', 'health', 'messaging', 'social', 'reports'
  ]::text[];
  v_enabled text[] := COALESCE(p_enabled_module_keys, ARRAY[]::text[]);
BEGIN
  IF v_club_id IS NULL OR v_role NOT IN ('coach', 'head_coach') THEN
    RAISE EXCEPTION 'Action réservée aux coachs.' USING ERRCODE = '42501';
  END IF;
  IF cardinality(v_ids) = 0 THEN
    RAISE EXCEPTION 'Sélectionne au moins un athlète.' USING ERRCODE = '22023';
  END IF;
  IF EXISTS (SELECT 1 FROM unnest(v_ids) athlete_id
             LEFT JOIN public.athletes a ON a.id = athlete_id
             WHERE a.id IS NULL OR a.club_id <> v_club_id) THEN
    RAISE EXCEPTION 'Athlète hors de ton effectif.' USING ERRCODE = '42501';
  END IF;
  IF EXISTS (SELECT 1 FROM unnest(v_enabled) key WHERE NOT key = ANY(v_allowed)) THEN
    RAISE EXCEPTION 'Module inconnu.' USING ERRCODE = '22023';
  END IF;
  IF 'training_load' = ANY(v_enabled) AND NOT ('session_feedback' = ANY(v_enabled)) THEN
    RAISE EXCEPTION 'La charge nécessite le feedback de séance.' USING ERRCODE = '23514';
  END IF;

  INSERT INTO public.athlete_modules (athlete_id, club_id, module_key, enabled, updated_by)
  SELECT athlete_id, v_club_id, key, key = ANY(v_enabled), v_user_id
  FROM unnest(v_ids) athlete_id CROSS JOIN unnest(v_allowed) key
  ON CONFLICT (athlete_id, module_key) DO UPDATE
    SET enabled = EXCLUDED.enabled, club_id = EXCLUDED.club_id, updated_by = EXCLUDED.updated_by;

  RETURN jsonb_build_object(
    'athleteIds', to_jsonb(v_ids),
    'enabledModuleKeys', to_jsonb(v_enabled)
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.reset_my_club_module_onboarding()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  IF public.get_my_role() <> 'head_coach' OR public.get_my_club_id() IS NULL THEN
    RAISE EXCEPTION 'Action réservée au head coach.' USING ERRCODE = '42501';
  END IF;
  UPDATE public.clubs SET modules_configured_at = NULL WHERE id = public.get_my_club_id();
END;
$$;

REVOKE ALL ON FUNCTION public.configure_my_club_modules(text[]) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.configure_athlete_modules(integer[], text[]) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.reset_my_club_module_onboarding() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.configure_my_club_modules(text[]) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.configure_athlete_modules(integer[], text[]) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.reset_my_club_module_onboarding() TO authenticated;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
    IF NOT EXISTS (
      SELECT 1 FROM pg_publication_tables
      WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'club_modules'
    ) THEN
      ALTER PUBLICATION supabase_realtime ADD TABLE public.club_modules;
    END IF;
    IF NOT EXISTS (
      SELECT 1 FROM pg_publication_tables
      WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'athlete_modules'
    ) THEN
      ALTER PUBLICATION supabase_realtime ADD TABLE public.athlete_modules;
    END IF;
  END IF;
END;
$$;

COMMIT;
