BEGIN;

-- ---------------------------------------------------------------------------
-- Un objet Storage unique, réutilisé par autant de séances et destinataires
-- que nécessaire. Les chemins restent dans le bucket privé historique afin
-- de conserver toute la validation/signature déjà en place.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.documents (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  club_id integer NOT NULL REFERENCES public.clubs(id) ON DELETE CASCADE,
  name text NOT NULL,
  storage_path text NOT NULL,
  mime_type text NOT NULL,
  size_bytes bigint NOT NULL DEFAULT 0,
  category text,
  tags text[] NOT NULL DEFAULT ARRAY[]::text[],
  uploaded_by integer REFERENCES public.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (club_id, storage_path),
  CONSTRAINT documents_name_check CHECK (char_length(btrim(name)) BETWEEN 1 AND 255),
  CONSTRAINT documents_size_check CHECK (size_bytes BETWEEN 0 AND 31457280)
);

CREATE TABLE IF NOT EXISTS public.session_documents (
  session_id integer NOT NULL REFERENCES public.sessions(id) ON DELETE CASCADE,
  document_id bigint NOT NULL REFERENCES public.documents(id) ON DELETE RESTRICT,
  visibility text NOT NULL DEFAULT 'all',
  attached_by integer REFERENCES public.users(id) ON DELETE SET NULL,
  attached_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (session_id, document_id),
  CONSTRAINT session_documents_visibility_check CHECK (visibility IN ('all', 'selected'))
);

CREATE TABLE IF NOT EXISTS public.session_document_recipients (
  session_id integer NOT NULL,
  document_id bigint NOT NULL,
  athlete_id integer NOT NULL REFERENCES public.athletes(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (session_id, document_id, athlete_id),
  FOREIGN KEY (session_id, document_id)
    REFERENCES public.session_documents(session_id, document_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.session_template_documents (
  template_id bigint NOT NULL REFERENCES public.session_templates(id) ON DELETE CASCADE,
  document_id bigint NOT NULL REFERENCES public.documents(id) ON DELETE RESTRICT,
  PRIMARY KEY (template_id, document_id)
);

CREATE TABLE IF NOT EXISTS public.session_series_documents (
  series_id bigint NOT NULL REFERENCES public.session_series(id) ON DELETE CASCADE,
  document_id bigint NOT NULL REFERENCES public.documents(id) ON DELETE RESTRICT,
  PRIMARY KEY (series_id, document_id)
);

CREATE TABLE IF NOT EXISTS public.planning_event_documents (
  event_id bigint NOT NULL REFERENCES public.planning_events(id) ON DELETE CASCADE,
  document_id bigint NOT NULL REFERENCES public.documents(id) ON DELETE RESTRICT,
  PRIMARY KEY (event_id, document_id)
);

CREATE INDEX IF NOT EXISTS documents_club_category_name_idx
  ON public.documents (club_id, category, lower(name));
CREATE INDEX IF NOT EXISTS session_documents_document_idx
  ON public.session_documents (document_id, session_id);
CREATE INDEX IF NOT EXISTS session_document_recipients_athlete_idx
  ON public.session_document_recipients (athlete_id, session_id, document_id);

-- Les anciens pdf_url deviennent des entrées de bibliothèque et des liens de
-- séance, sans déplacement ni duplication de l'objet Storage.
INSERT INTO public.documents (club_id, name, storage_path, mime_type, size_bytes, uploaded_by, created_at)
SELECT DISTINCT ON (session.club_id, session.pdf_url)
  session.club_id,
  coalesce(nullif(regexp_replace(session.pdf_url, '^.*/', ''), ''), 'Document historique'),
  session.pdf_url,
  'application/octet-stream',
  0,
  session.created_by,
  now()
FROM public.sessions session
WHERE nullif(session.pdf_url, '') IS NOT NULL
ON CONFLICT (club_id, storage_path) DO NOTHING;

INSERT INTO public.session_documents (session_id, document_id, visibility, attached_by)
SELECT session.id, document.id, 'all', session.created_by
FROM public.sessions session
JOIN public.documents document
  ON document.club_id = session.club_id AND document.storage_path = session.pdf_url
WHERE nullif(session.pdf_url, '') IS NOT NULL
ON CONFLICT (session_id, document_id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- Autorisations : le staff voit la bibliothèque du club. Un athlète ne voit
-- qu'un document lié à une séance/événement auquel il est réellement affecté.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.can_access_training_document(p_document_id bigint)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path TO 'public'
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.documents document
    WHERE document.id = p_document_id
      AND document.club_id = public.get_my_club_id()
      AND (
        public.get_my_role() IN ('head_coach', 'coach')
        OR EXISTS (
          SELECT 1
          FROM public.session_documents link
          JOIN public.session_athletes assignment ON assignment.session_id = link.session_id
          WHERE link.document_id = document.id
            AND assignment.athlete_id = public.get_my_athlete_id()
            AND (
              link.visibility = 'all'
              OR EXISTS (
                SELECT 1 FROM public.session_document_recipients recipient
                WHERE recipient.session_id = link.session_id
                  AND recipient.document_id = link.document_id
                  AND recipient.athlete_id = assignment.athlete_id
              )
            )
        )
        OR EXISTS (
          SELECT 1
          FROM public.planning_event_documents link
          JOIN public.planning_event_athletes assignment ON assignment.event_id = link.event_id
          WHERE link.document_id = document.id
            AND assignment.athlete_id = public.get_my_athlete_id()
        )
      )
  )
$$;

CREATE OR REPLACE FUNCTION public.can_access_training_document_path(p_storage_path text)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path TO 'public'
AS $$
  SELECT
    EXISTS (
      SELECT 1 FROM public.documents document
      WHERE document.storage_path = p_storage_path
        AND public.can_access_training_document(document.id)
    )
    OR EXISTS (
      SELECT 1
      FROM public.sessions session
      JOIN public.session_athletes assignment ON assignment.session_id = session.id
      WHERE session.pdf_url = p_storage_path
        AND session.club_id = public.get_my_club_id()
        AND (
          public.get_my_role() IN ('head_coach', 'coach')
          OR assignment.athlete_id = public.get_my_athlete_id()
        )
    )
$$;

CREATE OR REPLACE FUNCTION public.can_access_session_document_link(p_session_id integer,p_document_id bigint)
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public' AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.session_documents link
    JOIN public.sessions session ON session.id=link.session_id
    WHERE link.session_id=p_session_id AND link.document_id=p_document_id
      AND session.club_id=public.get_my_club_id()
      AND (
        public.get_my_role() IN ('head_coach','coach')
        OR EXISTS (
          SELECT 1 FROM public.session_athletes assignment
          WHERE assignment.session_id=link.session_id
            AND assignment.athlete_id=public.get_my_athlete_id()
            AND (
              link.visibility='all'
              OR EXISTS (
                SELECT 1 FROM public.session_document_recipients recipient
                WHERE recipient.session_id=link.session_id
                  AND recipient.document_id=link.document_id
                  AND recipient.athlete_id=assignment.athlete_id
              )
            )
        )
      )
  )
$$;

CREATE OR REPLACE FUNCTION public.can_access_planning_event_document_link(p_event_id bigint,p_document_id bigint)
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public' AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.planning_event_documents link
    JOIN public.planning_events event ON event.id=link.event_id
    WHERE link.event_id=p_event_id AND link.document_id=p_document_id
      AND event.club_id=public.get_my_club_id()
      AND (
        public.get_my_role() IN ('head_coach','coach')
        OR EXISTS (
          SELECT 1 FROM public.planning_event_athletes assignment
          WHERE assignment.event_id=link.event_id AND assignment.athlete_id=public.get_my_athlete_id()
        )
      )
  )
$$;

ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.session_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.session_document_recipients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.session_template_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.session_series_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.planning_event_documents ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS documents_authorized_read ON public.documents;
CREATE POLICY documents_authorized_read ON public.documents
  FOR SELECT TO authenticated USING (public.can_access_training_document(id));
DROP POLICY IF EXISTS documents_staff_insert ON public.documents;
CREATE POLICY documents_staff_insert ON public.documents
  FOR INSERT TO authenticated WITH CHECK (
    club_id = public.get_my_club_id()
    AND public.get_my_role() IN ('head_coach', 'coach')
    AND uploaded_by = public.get_my_user_id()
  );
DROP POLICY IF EXISTS documents_staff_update ON public.documents;
CREATE POLICY documents_staff_update ON public.documents
  FOR UPDATE TO authenticated
  USING (club_id = public.get_my_club_id() AND public.get_my_role() IN ('head_coach', 'coach'))
  WITH CHECK (club_id = public.get_my_club_id() AND public.get_my_role() IN ('head_coach', 'coach'));
DROP POLICY IF EXISTS documents_staff_delete ON public.documents;
CREATE POLICY documents_staff_delete ON public.documents
  FOR DELETE TO authenticated
  USING (club_id = public.get_my_club_id() AND public.get_my_role() IN ('head_coach', 'coach'));

DROP POLICY IF EXISTS session_documents_authorized_read ON public.session_documents;
CREATE POLICY session_documents_authorized_read ON public.session_documents
  FOR SELECT TO authenticated USING (public.can_access_session_document_link(session_id,document_id));
DROP POLICY IF EXISTS session_documents_staff_manage ON public.session_documents;
CREATE POLICY session_documents_staff_manage ON public.session_documents
  FOR ALL TO authenticated
  USING (public.get_my_role() IN ('head_coach','coach') AND EXISTS (
    SELECT 1 FROM public.sessions session WHERE session.id=session_id AND session.club_id=public.get_my_club_id()
  ))
  WITH CHECK (public.get_my_role() IN ('head_coach','coach') AND EXISTS (
    SELECT 1 FROM public.sessions session WHERE session.id=session_id AND session.club_id=public.get_my_club_id()
  ) AND EXISTS (
    SELECT 1 FROM public.documents document WHERE document.id=document_id AND document.club_id=public.get_my_club_id()
  ));

DROP POLICY IF EXISTS session_document_recipients_authorized_read ON public.session_document_recipients;
CREATE POLICY session_document_recipients_authorized_read ON public.session_document_recipients
  FOR SELECT TO authenticated USING (
    public.get_my_role() IN ('head_coach','coach')
      AND public.can_access_session_document_link(session_id,document_id)
    OR athlete_id=public.get_my_athlete_id()
      AND public.can_access_session_document_link(session_id,document_id)
  );
DROP POLICY IF EXISTS session_document_recipients_staff_manage ON public.session_document_recipients;
CREATE POLICY session_document_recipients_staff_manage ON public.session_document_recipients
  FOR ALL TO authenticated
  USING (public.get_my_role() IN ('head_coach','coach') AND EXISTS (
    SELECT 1 FROM public.sessions session WHERE session.id=session_id AND session.club_id=public.get_my_club_id()
  ))
  WITH CHECK (
    public.get_my_role() IN ('head_coach','coach')
    AND EXISTS (SELECT 1 FROM public.sessions session WHERE session.id=session_id AND session.club_id=public.get_my_club_id())
    AND EXISTS (SELECT 1 FROM public.athletes athlete WHERE athlete.id=athlete_id AND athlete.club_id=public.get_my_club_id())
  );

DROP POLICY IF EXISTS session_template_documents_club ON public.session_template_documents;
CREATE POLICY session_template_documents_club ON public.session_template_documents FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM public.session_templates template WHERE template.id=template_id AND template.club_id=public.get_my_club_id()))
  WITH CHECK (public.get_my_role() IN ('head_coach','coach')
    AND EXISTS (SELECT 1 FROM public.session_templates template WHERE template.id=template_id AND template.club_id=public.get_my_club_id())
    AND EXISTS (SELECT 1 FROM public.documents document WHERE document.id=document_id AND document.club_id=public.get_my_club_id()));
DROP POLICY IF EXISTS session_series_documents_club ON public.session_series_documents;
CREATE POLICY session_series_documents_club ON public.session_series_documents FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM public.session_series series WHERE series.id=series_id AND series.club_id=public.get_my_club_id()))
  WITH CHECK (public.get_my_role() IN ('head_coach','coach')
    AND EXISTS (SELECT 1 FROM public.session_series series WHERE series.id=series_id AND series.club_id=public.get_my_club_id())
    AND EXISTS (SELECT 1 FROM public.documents document WHERE document.id=document_id AND document.club_id=public.get_my_club_id()));
DROP POLICY IF EXISTS planning_event_documents_club ON public.planning_event_documents;
CREATE POLICY planning_event_documents_club ON public.planning_event_documents FOR ALL TO authenticated
  USING (public.can_access_planning_event_document_link(event_id,document_id))
  WITH CHECK (public.get_my_role() IN ('head_coach','coach')
    AND EXISTS (SELECT 1 FROM public.planning_events event WHERE event.id=event_id AND event.club_id=public.get_my_club_id())
    AND EXISTS (SELECT 1 FROM public.documents document WHERE document.id=document_id AND document.club_id=public.get_my_club_id()));

GRANT SELECT, INSERT, UPDATE, DELETE ON public.documents, public.session_documents,
  public.session_document_recipients, public.session_template_documents,
  public.session_series_documents, public.planning_event_documents TO authenticated;

-- Enregistrement atomique des métadonnées après l'upload. Le client ne doit
-- pas dépendre d'un INSERT ... RETURNING soumis à la policy SELECT avant que
-- le document ne soit lié à une séance.
CREATE OR REPLACE FUNCTION public.register_training_document(
  p_name text,
  p_storage_path text,
  p_mime_type text,
  p_size_bytes bigint,
  p_category text DEFAULT NULL,
  p_tags text[] DEFAULT ARRAY[]::text[]
) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $$
DECLARE v_document public.documents%ROWTYPE; v_club_id integer:=public.get_my_club_id();
BEGIN
  IF public.get_my_role() NOT IN ('head_coach','coach') THEN RAISE EXCEPTION 'Action non autorisee.'; END IF;
  IF split_part(p_storage_path,'/',1) <> v_club_id::text THEN RAISE EXCEPTION 'Chemin Storage invalide.'; END IF;
  INSERT INTO public.documents (club_id,name,storage_path,mime_type,size_bytes,category,tags,uploaded_by)
  VALUES (v_club_id,btrim(p_name),p_storage_path,p_mime_type,p_size_bytes,nullif(p_category,''),coalesce(p_tags,ARRAY[]::text[]),public.get_my_user_id())
  RETURNING * INTO v_document;
  RETURN to_jsonb(v_document);
END;
$$;

-- Storage : remplace la lecture large "membre du même club" par la décision
-- d'accès ci-dessus. Les uploads restent club-scoped et à chemin aléatoire.
DROP POLICY IF EXISTS "club-scoped read session-pdfs" ON storage.objects;
CREATE POLICY "assigned read session-pdfs" ON storage.objects
  FOR SELECT TO authenticated
  USING (bucket_id='session-pdfs' AND public.can_access_training_document_path(name));

DROP POLICY IF EXISTS "club-scoped update session-pdfs" ON storage.objects;
CREATE POLICY "staff update session-pdfs" ON storage.objects
  FOR UPDATE TO authenticated
  USING (
    bucket_id='session-pdfs'
    AND (storage.foldername(name))[1]=public.get_my_club_id()::text
    AND public.get_my_role() IN ('head_coach','coach')
  )
  WITH CHECK (
    bucket_id='session-pdfs'
    AND (storage.foldername(name))[1]=public.get_my_club_id()::text
    AND public.get_my_role() IN ('head_coach','coach')
  );
DROP POLICY IF EXISTS "club-scoped delete session-pdfs" ON storage.objects;
CREATE POLICY "staff delete session-pdfs" ON storage.objects
  FOR DELETE TO authenticated
  USING (
    bucket_id='session-pdfs'
    AND (storage.foldername(name))[1]=public.get_my_club_id()::text
    AND public.get_my_role() IN ('head_coach','coach')
  );

-- ---------------------------------------------------------------------------
-- Publication en batch : 1 RPC, zéro requête par athlète.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.publish_session_documents(
  p_session_id integer,
  p_document_ids bigint[],
  p_athlete_ids integer[] DEFAULT NULL,
  p_notification_key text DEFAULT NULL
) RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_club_id integer := public.get_my_club_id();
  v_user_id integer := public.get_my_user_id();
  v_targets integer[];
  v_new_document_ids bigint[];
  v_visibility text := CASE WHEN p_athlete_ids IS NULL THEN 'all' ELSE 'selected' END;
  v_notification_key text := coalesce(nullif(p_notification_key,''), gen_random_uuid()::text);
  v_associations integer := 0;
BEGIN
  IF v_user_id IS NULL OR public.get_my_role() NOT IN ('head_coach','coach') THEN RAISE EXCEPTION 'Action non autorisee.'; END IF;
  IF NOT EXISTS (SELECT 1 FROM public.sessions session WHERE session.id=p_session_id AND session.club_id=v_club_id) THEN
    RAISE EXCEPTION 'Seance introuvable.';
  END IF;
  -- L'appel représente l'état complet du formulaire : retirer en une seule
  -- écriture les documents désélectionnés, sans supprimer l'objet de la
  -- bibliothèque ni les liens éventuels vers d'autres séances.
  DELETE FROM public.session_documents link
  WHERE link.session_id=p_session_id
    AND NOT (link.document_id=ANY(coalesce(p_document_ids,ARRAY[]::bigint[])));
  IF cardinality(coalesce(p_document_ids, ARRAY[]::bigint[])) = 0 THEN
    RETURN jsonb_build_object('documentCount',0,'recipientCount',0,'associationCount',0);
  END IF;
  IF (SELECT count(DISTINCT id) FROM unnest(p_document_ids) id) <> cardinality(p_document_ids) THEN
    RAISE EXCEPTION 'Un document ne peut etre associe qu une fois.';
  END IF;
  IF EXISTS (SELECT 1 FROM unnest(p_document_ids) id WHERE NOT EXISTS (
    SELECT 1 FROM public.documents document WHERE document.id=id AND document.club_id=v_club_id
  )) THEN RAISE EXCEPTION 'Un document n appartient pas au club.'; END IF;

  SELECT array_agg(assignment.athlete_id ORDER BY assignment.athlete_id) INTO v_targets
  FROM public.session_athletes assignment
  WHERE assignment.session_id=p_session_id
    AND (p_athlete_ids IS NULL OR assignment.athlete_id=ANY(p_athlete_ids));
  IF cardinality(coalesce(v_targets,ARRAY[]::integer[])) = 0 THEN RAISE EXCEPTION 'Aucun destinataire autorise.'; END IF;
  IF p_athlete_ids IS NOT NULL AND cardinality(v_targets) <> (SELECT count(DISTINCT id) FROM unnest(p_athlete_ids) id) THEN
    RAISE EXCEPTION 'Un athlete destinataire n est pas assigne a la seance.';
  END IF;

  SELECT array_agg(id) INTO v_new_document_ids
  FROM unnest(p_document_ids) id
  WHERE NOT EXISTS (SELECT 1 FROM public.session_documents link WHERE link.session_id=p_session_id AND link.document_id=id);

  INSERT INTO public.session_documents (session_id,document_id,visibility,attached_by)
  SELECT p_session_id,id,v_visibility,v_user_id FROM unnest(p_document_ids) id
  ON CONFLICT (session_id,document_id) DO UPDATE SET visibility=EXCLUDED.visibility;

  DELETE FROM public.session_document_recipients recipient
  WHERE recipient.session_id=p_session_id AND recipient.document_id=ANY(p_document_ids);
  IF v_visibility='selected' THEN
    INSERT INTO public.session_document_recipients (session_id,document_id,athlete_id)
    SELECT p_session_id,document_id,athlete_id
    FROM unnest(p_document_ids) document_id CROSS JOIN unnest(v_targets) athlete_id
    ON CONFLICT DO NOTHING;
    GET DIAGNOSTICS v_associations = ROW_COUNT;
  ELSE
    v_associations := cardinality(p_document_ids) * cardinality(v_targets);
  END IF;

  IF cardinality(coalesce(v_new_document_ids,ARRAY[]::bigint[])) > 0 THEN
    INSERT INTO public.athlete_notifications (
      athlete_id,club_id,type,title,description,is_read,session_id,dedupe_key
    )
    SELECT athlete_id,v_club_id,'training_document','Nouveau document d''entraînement disponible',
      CASE WHEN cardinality(v_new_document_ids)=1 THEN 'Un nouveau document est disponible dans ta séance.'
           ELSE cardinality(v_new_document_ids)||' nouveaux documents sont disponibles dans ta séance.' END,
      false,p_session_id,'session-documents-'||p_session_id||'-'||v_notification_key
    FROM unnest(v_targets) athlete_id
    ON CONFLICT (athlete_id,type,dedupe_key) DO NOTHING;
  END IF;
  RETURN jsonb_build_object(
    'documentCount',cardinality(p_document_ids), 'newDocumentCount',cardinality(coalesce(v_new_document_ids,ARRAY[]::bigint[])),
    'recipientCount',cardinality(v_targets), 'associationCount',v_associations,
    'physicalUploadCount',0
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.detach_session_document(p_session_id integer,p_document_id bigint)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $$
BEGIN
  IF public.get_my_role() NOT IN ('head_coach','coach') OR NOT EXISTS (
    SELECT 1 FROM public.sessions session WHERE session.id=p_session_id AND session.club_id=public.get_my_club_id()
  ) THEN RAISE EXCEPTION 'Action non autorisee.'; END IF;
  DELETE FROM public.session_documents WHERE session_id=p_session_id AND document_id=p_document_id;
  RETURN jsonb_build_object('sessionId',p_session_id,'documentId',p_document_id);
END;
$$;

-- Variante structurée : chaque document peut viser tous les athlètes de la
-- séance ou son propre sous-ensemble. Toute la distribution est validée et
-- écrite dans une seule transaction, quel que soit le nombre d'athlètes.
CREATE OR REPLACE FUNCTION public.publish_session_document_distribution(
  p_session_id integer,
  p_distribution jsonb,
  p_notification_key text DEFAULT NULL
) RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_club_id integer := public.get_my_club_id();
  v_user_id integer := public.get_my_user_id();
  v_items jsonb := coalesce(p_distribution,'[]'::jsonb);
  v_new_document_ids bigint[];
  v_notification_key text := coalesce(nullif(p_notification_key,''),gen_random_uuid()::text);
  v_document_count integer := 0;
  v_recipient_count integer := 0;
  v_association_count integer := 0;
BEGIN
  IF v_user_id IS NULL OR public.get_my_role() NOT IN ('head_coach','coach') THEN
    RAISE EXCEPTION 'Action non autorisee.';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM public.sessions session WHERE session.id=p_session_id AND session.club_id=v_club_id) THEN
    RAISE EXCEPTION 'Seance introuvable.';
  END IF;
  IF jsonb_typeof(v_items) <> 'array' THEN RAISE EXCEPTION 'Distribution documentaire invalide.'; END IF;
  IF EXISTS (
    SELECT 1 FROM jsonb_array_elements(v_items) item
    WHERE jsonb_typeof(item) <> 'object'
      OR nullif(item->>'documentId','') IS NULL
      OR (item ? 'athleteIds' AND jsonb_typeof(item->'athleteIds') NOT IN ('array','null'))
  ) THEN RAISE EXCEPTION 'Distribution documentaire invalide.'; END IF;
  IF (SELECT count(*) FROM jsonb_array_elements(v_items)) <>
     (SELECT count(DISTINCT (item->>'documentId')::bigint) FROM jsonb_array_elements(v_items) item) THEN
    RAISE EXCEPTION 'Un document ne peut etre associe qu une fois.';
  END IF;
  IF EXISTS (
    SELECT 1 FROM jsonb_array_elements(v_items) item
    WHERE NOT EXISTS (
      SELECT 1 FROM public.documents document
      WHERE document.id=(item->>'documentId')::bigint AND document.club_id=v_club_id
    )
  ) THEN RAISE EXCEPTION 'Un document n appartient pas au club.'; END IF;
  IF EXISTS (
    SELECT 1 FROM jsonb_array_elements(v_items) item
    WHERE jsonb_typeof(item->'athleteIds')='array' AND jsonb_array_length(item->'athleteIds')=0
  ) THEN RAISE EXCEPTION 'Un document cible doit avoir au moins un destinataire.'; END IF;
  IF EXISTS (
    SELECT 1
    FROM jsonb_array_elements(v_items) item
    CROSS JOIN LATERAL jsonb_array_elements_text(
      CASE WHEN jsonb_typeof(item->'athleteIds')='array' THEN item->'athleteIds' ELSE '[]'::jsonb END
    ) athlete_id
    WHERE jsonb_typeof(item->'athleteIds')='array'
      AND NOT EXISTS (
        SELECT 1 FROM public.session_athletes assignment
        WHERE assignment.session_id=p_session_id AND assignment.athlete_id=athlete_id::integer
      )
  ) THEN RAISE EXCEPTION 'Un athlete destinataire n est pas assigne a la seance.'; END IF;

  SELECT array_agg((item->>'documentId')::bigint) INTO v_new_document_ids
  FROM jsonb_array_elements(v_items) item
  WHERE NOT EXISTS (
    SELECT 1 FROM public.session_documents link
    WHERE link.session_id=p_session_id AND link.document_id=(item->>'documentId')::bigint
  );

  DELETE FROM public.session_documents link
  WHERE link.session_id=p_session_id
    AND NOT EXISTS (
      SELECT 1 FROM jsonb_array_elements(v_items) item
      WHERE (item->>'documentId')::bigint=link.document_id
    );

  INSERT INTO public.session_documents(session_id,document_id,visibility,attached_by)
  SELECT p_session_id,(item->>'documentId')::bigint,
    CASE WHEN jsonb_typeof(item->'athleteIds')='array' THEN 'selected' ELSE 'all' END,
    v_user_id
  FROM jsonb_array_elements(v_items) item
  ON CONFLICT(session_id,document_id) DO UPDATE SET visibility=EXCLUDED.visibility;

  DELETE FROM public.session_document_recipients recipient WHERE recipient.session_id=p_session_id;
  INSERT INTO public.session_document_recipients(session_id,document_id,athlete_id)
  SELECT p_session_id,(item->>'documentId')::bigint,athlete_id::integer
  FROM jsonb_array_elements(v_items) item
  CROSS JOIN LATERAL jsonb_array_elements_text(
    CASE WHEN jsonb_typeof(item->'athleteIds')='array' THEN item->'athleteIds' ELSE '[]'::jsonb END
  ) athlete_id
  WHERE jsonb_typeof(item->'athleteIds')='array'
  ON CONFLICT DO NOTHING;

  SELECT count(*) INTO v_document_count FROM jsonb_array_elements(v_items);
  SELECT count(DISTINCT assignment.athlete_id),count(*)
    INTO v_recipient_count,v_association_count
  FROM jsonb_array_elements(v_items) item
  JOIN public.session_athletes assignment ON assignment.session_id=p_session_id
    AND (
      coalesce(jsonb_typeof(item->'athleteIds'),'null') <> 'array'
      OR EXISTS (
        SELECT 1 FROM jsonb_array_elements_text(
          CASE WHEN jsonb_typeof(item->'athleteIds')='array' THEN item->'athleteIds' ELSE '[]'::jsonb END
        ) target
        WHERE target::integer=assignment.athlete_id
      )
    );

  IF cardinality(coalesce(v_new_document_ids,ARRAY[]::bigint[])) > 0 THEN
    INSERT INTO public.athlete_notifications(
      athlete_id,club_id,type,title,description,is_read,session_id,dedupe_key
    )
    SELECT DISTINCT assignment.athlete_id,v_club_id,'training_document',
      'Nouveau document d''entraînement disponible',
      CASE WHEN cardinality(v_new_document_ids)=1 THEN 'Un nouveau document est disponible dans ta séance.'
           ELSE cardinality(v_new_document_ids)||' nouveaux documents sont disponibles dans ta séance.' END,
      false,p_session_id,'session-documents-'||p_session_id||'-'||v_notification_key
    FROM jsonb_array_elements(v_items) item
    JOIN public.session_athletes assignment ON assignment.session_id=p_session_id
      AND (
        coalesce(jsonb_typeof(item->'athleteIds'),'null') <> 'array'
        OR EXISTS (
          SELECT 1 FROM jsonb_array_elements_text(
            CASE WHEN jsonb_typeof(item->'athleteIds')='array' THEN item->'athleteIds' ELSE '[]'::jsonb END
          ) target
          WHERE target::integer=assignment.athlete_id
        )
      )
    WHERE (item->>'documentId')::bigint=ANY(v_new_document_ids)
    ON CONFLICT(athlete_id,type,dedupe_key) DO NOTHING;
  END IF;

  RETURN jsonb_build_object(
    'documentCount',v_document_count,
    'newDocumentCount',cardinality(coalesce(v_new_document_ids,ARRAY[]::bigint[])),
    'recipientCount',v_recipient_count,
    'associationCount',v_association_count,
    'physicalUploadCount',0
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.delete_document_transactional(p_document_id bigint)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $$
DECLARE v_document public.documents%ROWTYPE;
BEGIN
  IF public.get_my_role() NOT IN ('head_coach','coach') THEN RAISE EXCEPTION 'Action non autorisee.'; END IF;
  SELECT * INTO v_document FROM public.documents WHERE id=p_document_id AND club_id=public.get_my_club_id() FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Document introuvable.'; END IF;
  IF EXISTS (SELECT 1 FROM public.session_documents WHERE document_id=p_document_id)
    OR EXISTS (SELECT 1 FROM public.session_template_documents WHERE document_id=p_document_id)
    OR EXISTS (SELECT 1 FROM public.session_series_documents WHERE document_id=p_document_id)
    OR EXISTS (SELECT 1 FROM public.planning_event_documents WHERE document_id=p_document_id) THEN
    RAISE EXCEPTION 'Ce document est encore utilise. Retire d abord ses associations.';
  END IF;
  DELETE FROM public.documents WHERE id=p_document_id;
  RETURN jsonb_build_object('documentId',p_document_id,'storagePath',v_document.storage_path);
END;
$$;

CREATE OR REPLACE FUNCTION public.copy_parent_session_documents()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $$
BEGIN
  IF NEW.parent_session_id IS NULL THEN RETURN NEW; END IF;
  INSERT INTO public.session_documents (session_id,document_id,visibility,attached_by)
  SELECT NEW.id,document_id,visibility,NEW.created_by FROM public.session_documents
  WHERE session_id=NEW.parent_session_id ON CONFLICT DO NOTHING;
  INSERT INTO public.session_document_recipients (session_id,document_id,athlete_id)
  SELECT NEW.id,recipient.document_id,recipient.athlete_id
  FROM public.session_document_recipients recipient
  JOIN public.session_athletes assignment ON assignment.session_id=NEW.id AND assignment.athlete_id=recipient.athlete_id
  WHERE recipient.session_id=NEW.parent_session_id ON CONFLICT DO NOTHING;
  RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS sessions_copy_parent_documents ON public.sessions;
CREATE TRIGGER sessions_copy_parent_documents AFTER INSERT ON public.sessions
FOR EACH ROW EXECUTE FUNCTION public.copy_parent_session_documents();

CREATE OR REPLACE FUNCTION public.copy_parent_document_recipient()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $$
DECLARE v_parent_id integer;
BEGIN
  SELECT parent_session_id INTO v_parent_id FROM public.sessions WHERE id=NEW.session_id;
  IF v_parent_id IS NULL THEN RETURN NEW; END IF;
  INSERT INTO public.session_document_recipients(session_id,document_id,athlete_id)
  SELECT NEW.session_id,recipient.document_id,NEW.athlete_id
  FROM public.session_document_recipients recipient
  WHERE recipient.session_id=v_parent_id AND recipient.athlete_id=NEW.athlete_id
  ON CONFLICT DO NOTHING;
  RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS session_athletes_copy_parent_document_recipient ON public.session_athletes;
CREATE TRIGGER session_athletes_copy_parent_document_recipient AFTER INSERT ON public.session_athletes
FOR EACH ROW EXECUTE FUNCTION public.copy_parent_document_recipient();

CREATE OR REPLACE FUNCTION public.publish_series_documents(
  p_series_id bigint,
  p_document_ids bigint[],
  p_notification_key text DEFAULT NULL,
  p_from_date date DEFAULT current_date
)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $$
DECLARE
  v_club_id integer:=public.get_my_club_id();
  v_user_id integer:=public.get_my_user_id();
  v_session_ids integer[];
  v_targets integer[];
  v_previous_document_ids bigint[];
  v_new_document_ids bigint[];
  v_occurrence_count integer:=0;
  v_association_count integer:=0;
BEGIN
  IF public.get_my_role() NOT IN ('head_coach','coach') OR NOT EXISTS (
    SELECT 1 FROM public.session_series series WHERE series.id=p_series_id AND series.club_id=v_club_id
  ) THEN RAISE EXCEPTION 'Action non autorisee.'; END IF;
  IF (SELECT count(DISTINCT id) FROM unnest(coalesce(p_document_ids,ARRAY[]::bigint[])) id)
      <> cardinality(coalesce(p_document_ids,ARRAY[]::bigint[])) THEN
    RAISE EXCEPTION 'Un document ne peut etre associe qu une fois.';
  END IF;
  IF EXISTS (SELECT 1 FROM unnest(coalesce(p_document_ids,ARRAY[]::bigint[])) id WHERE NOT EXISTS (
    SELECT 1 FROM public.documents document WHERE document.id=id AND document.club_id=v_club_id
  )) THEN RAISE EXCEPTION 'Un document n appartient pas au club.'; END IF;

  SELECT array_agg(document_id) INTO v_previous_document_ids
  FROM public.session_series_documents WHERE series_id=p_series_id;
  SELECT array_agg(id) INTO v_new_document_ids
  FROM unnest(coalesce(p_document_ids,ARRAY[]::bigint[])) id
  WHERE NOT (id=ANY(coalesce(v_previous_document_ids,ARRAY[]::bigint[])));
  SELECT array_agg(id ORDER BY session_date,id),count(*) INTO v_session_ids,v_occurrence_count
  FROM public.sessions WHERE series_id=p_series_id AND session_date>=coalesce(p_from_date,current_date);

  -- Le formulaire représente l'état complet pour la portée choisie. Les
  -- objets Storage et leurs autres usages ne sont jamais supprimés.
  IF cardinality(coalesce(v_session_ids,ARRAY[]::integer[]))>0
     AND cardinality(coalesce(v_previous_document_ids,ARRAY[]::bigint[]))>0 THEN
    DELETE FROM public.session_documents link
    WHERE link.session_id=ANY(v_session_ids)
      AND link.document_id=ANY(v_previous_document_ids)
      AND NOT (link.document_id=ANY(coalesce(p_document_ids,ARRAY[]::bigint[])));
  END IF;
  DELETE FROM public.session_series_documents WHERE series_id=p_series_id
    AND NOT (document_id=ANY(coalesce(p_document_ids,ARRAY[]::bigint[])));
  INSERT INTO public.session_series_documents(series_id,document_id)
  SELECT p_series_id,id FROM unnest(coalesce(p_document_ids,ARRAY[]::bigint[])) id ON CONFLICT DO NOTHING;
  IF cardinality(coalesce(v_session_ids,ARRAY[]::integer[]))>0 THEN
    INSERT INTO public.session_documents(session_id,document_id,visibility,attached_by)
    SELECT session_id,document_id,'all',v_user_id
    FROM unnest(v_session_ids) session_id
    CROSS JOIN unnest(coalesce(p_document_ids,ARRAY[]::bigint[])) document_id
    ON CONFLICT(session_id,document_id) DO UPDATE SET visibility='all';
    DELETE FROM public.session_document_recipients recipient
    WHERE recipient.session_id=ANY(v_session_ids)
      AND recipient.document_id=ANY(coalesce(p_document_ids,ARRAY[]::bigint[]));
    SELECT array_agg(DISTINCT assignment.athlete_id ORDER BY assignment.athlete_id) INTO v_targets
    FROM public.session_athletes assignment WHERE assignment.session_id=ANY(v_session_ids);
    v_association_count:=v_occurrence_count
      * cardinality(coalesce(p_document_ids,ARRAY[]::bigint[]))
      * cardinality(coalesce(v_targets,ARRAY[]::integer[]));
  END IF;
  IF cardinality(coalesce(v_new_document_ids,ARRAY[]::bigint[]))>0 THEN
    INSERT INTO public.athlete_notifications(athlete_id,club_id,type,title,description,is_read,dedupe_key)
    SELECT athlete_id,v_club_id,'training_document','Nouveau document d''entraînement disponible',
      CASE WHEN cardinality(v_new_document_ids)=1 THEN 'Un nouveau document est disponible dans ta série de séances.'
           ELSE cardinality(v_new_document_ids)||' nouveaux documents sont disponibles dans ta série de séances.' END,
      false,'series-documents-'||p_series_id||'-'||coalesce(nullif(p_notification_key,''),gen_random_uuid()::text)
    FROM unnest(coalesce(v_targets,ARRAY[]::integer[])) athlete_id
    ON CONFLICT (athlete_id,type,dedupe_key) DO NOTHING;
  END IF;
  RETURN jsonb_build_object('seriesId',p_series_id,'occurrenceCount',v_occurrence_count,
    'documentCount',cardinality(coalesce(p_document_ids,ARRAY[]::bigint[])),
    'recipientCount',cardinality(coalesce(v_targets,ARRAY[]::integer[])),
    'associationCount',v_association_count,'physicalUploadCount',0);
END;
$$;

-- Même modèle pour un stage/test/événement : le fichier reste unique dans
-- Storage et tous les liens ainsi que les notifications sont créés en batch.
CREATE OR REPLACE FUNCTION public.publish_planning_event_documents(
  p_event_id bigint,
  p_document_ids bigint[],
  p_notification_key text DEFAULT NULL
) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $$
DECLARE
  v_club_id integer := public.get_my_club_id();
  v_targets integer[];
  v_new_document_ids bigint[];
  v_notification_key text := coalesce(nullif(p_notification_key,''), gen_random_uuid()::text);
BEGIN
  IF public.get_my_role() NOT IN ('head_coach','coach') OR NOT EXISTS (
    SELECT 1 FROM public.planning_events event WHERE event.id=p_event_id AND event.club_id=v_club_id
  ) THEN RAISE EXCEPTION 'Action non autorisee.'; END IF;
  IF (SELECT count(DISTINCT id) FROM unnest(coalesce(p_document_ids,ARRAY[]::bigint[])) id)
      <> cardinality(coalesce(p_document_ids,ARRAY[]::bigint[])) THEN
    RAISE EXCEPTION 'Un document ne peut etre associe qu une fois.';
  END IF;
  IF EXISTS (SELECT 1 FROM unnest(coalesce(p_document_ids,ARRAY[]::bigint[])) id WHERE NOT EXISTS (
    SELECT 1 FROM public.documents document WHERE document.id=id AND document.club_id=v_club_id
  )) THEN RAISE EXCEPTION 'Un document n appartient pas au club.'; END IF;

  SELECT array_agg(id) INTO v_new_document_ids
  FROM unnest(coalesce(p_document_ids,ARRAY[]::bigint[])) id
  WHERE NOT EXISTS (
    SELECT 1 FROM public.planning_event_documents link
    WHERE link.event_id=p_event_id AND link.document_id=id
  );

  DELETE FROM public.planning_event_documents link
  WHERE link.event_id=p_event_id
    AND NOT (link.document_id=ANY(coalesce(p_document_ids,ARRAY[]::bigint[])));
  INSERT INTO public.planning_event_documents(event_id,document_id)
  SELECT p_event_id,id FROM unnest(coalesce(p_document_ids,ARRAY[]::bigint[])) id
  ON CONFLICT DO NOTHING;

  SELECT array_agg(assignment.athlete_id ORDER BY assignment.athlete_id) INTO v_targets
  FROM public.planning_event_athletes assignment WHERE assignment.event_id=p_event_id;
  IF cardinality(coalesce(v_new_document_ids,ARRAY[]::bigint[]))>0 THEN
    INSERT INTO public.athlete_notifications(athlete_id,club_id,type,title,description,is_read,dedupe_key)
    SELECT athlete_id,v_club_id,'training_document','Nouveau document d''entraînement disponible',
      CASE WHEN cardinality(v_new_document_ids)=1 THEN 'Un nouveau document est disponible dans ton événement.'
           ELSE cardinality(v_new_document_ids)||' nouveaux documents sont disponibles dans ton événement.' END,
      false,'event-documents-'||p_event_id||'-'||v_notification_key
    FROM unnest(coalesce(v_targets,ARRAY[]::integer[])) athlete_id
    ON CONFLICT (athlete_id,type,dedupe_key) DO NOTHING;
  END IF;
  RETURN jsonb_build_object(
    'eventId',p_event_id,
    'documentCount',cardinality(coalesce(p_document_ids,ARRAY[]::bigint[])),
    'newDocumentCount',cardinality(coalesce(v_new_document_ids,ARRAY[]::bigint[])),
    'recipientCount',cardinality(coalesce(v_targets,ARRAY[]::integer[])),
    'physicalUploadCount',0
  );
END;
$$;

-- Les modèles gardent les références aux fichiers, jamais une copie Storage.
CREATE OR REPLACE FUNCTION public.save_session_template(p_name text, p_session_id integer)
RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $$
DECLARE v_id bigint;
BEGIN
  IF public.get_my_role() NOT IN ('head_coach','coach') THEN RAISE EXCEPTION 'Action non autorisee.'; END IF;
  INSERT INTO public.session_templates (club_id,name,category,type,training_focus,title,duration_minutes,description,instructions,created_by)
  SELECT club_id,btrim(p_name),category,type,training_focus,title,duration_minutes,description,instructions,public.get_my_user_id()
  FROM public.sessions WHERE id=p_session_id AND club_id=public.get_my_club_id()
  ON CONFLICT (club_id,name) DO UPDATE SET category=EXCLUDED.category,type=EXCLUDED.type,
    training_focus=EXCLUDED.training_focus,title=EXCLUDED.title,duration_minutes=EXCLUDED.duration_minutes,
    description=EXCLUDED.description,instructions=EXCLUDED.instructions,updated_at=now()
  RETURNING id INTO v_id;
  IF v_id IS NULL THEN RAISE EXCEPTION 'Seance introuvable.'; END IF;
  DELETE FROM public.session_template_documents WHERE template_id=v_id;
  INSERT INTO public.session_template_documents(template_id,document_id)
  SELECT v_id,document_id FROM public.session_documents WHERE session_id=p_session_id ON CONFLICT DO NOTHING;
  RETURN v_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.create_session_from_template(
  p_template_id bigint,
  p_schedule jsonb,
  p_athlete_ids integer[],
  p_idempotency_key text DEFAULT NULL
) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $$
DECLARE v_template public.session_templates%ROWTYPE; v_result jsonb; v_document_ids bigint[];
BEGIN
  SELECT * INTO v_template FROM public.session_templates
  WHERE id=p_template_id AND club_id=public.get_my_club_id();
  IF NOT FOUND THEN RAISE EXCEPTION 'Modele introuvable.'; END IF;
  v_result:=public.create_session_with_athletes(jsonb_build_object(
    'title',v_template.title,'category',v_template.category,'type',v_template.type,
    'trainingFocus',v_template.training_focus,'durationMinutes',v_template.duration_minutes,
    'description',v_template.description,'instructions',v_template.instructions
  )||p_schedule,p_athlete_ids,p_idempotency_key);
  UPDATE public.sessions SET source_kind='template' WHERE id=(v_result->>'sessionId')::integer;
  SELECT array_agg(document_id) INTO v_document_ids FROM public.session_template_documents WHERE template_id=p_template_id;
  IF cardinality(coalesce(v_document_ids,ARRAY[]::bigint[]))>0 THEN
    PERFORM public.publish_session_documents((v_result->>'sessionId')::integer,v_document_ids,NULL,p_idempotency_key);
  END IF;
  RETURN v_result||jsonb_build_object('documentCount',cardinality(coalesce(v_document_ids,ARRAY[]::bigint[])));
END;
$$;

CREATE OR REPLACE FUNCTION public.module_key_for_notification_type(p_type text)
RETURNS text LANGUAGE sql IMMUTABLE SET search_path = public, pg_temp AS $$
  SELECT CASE
    WHEN p_type IN ('new_session','session_updated','session_day_reminder','session_response','athlete_session','training_document') THEN 'planning'
    WHEN p_type IN ('session_feedback_reminder','weekly_recap','recap','absence') THEN 'session_feedback'
    WHEN p_type IN ('result_added','goal_achieved','competition_reminder','competition','performance') THEN 'performances'
    WHEN p_type='weekly_report' THEN 'reports'
    WHEN p_type='message' THEN 'messaging'
    WHEN p_type IN ('social_post','social') THEN 'social'
    WHEN p_type IN ('blessure','injury') THEN 'health'
    WHEN p_type='wellness' THEN 'wellness'
    WHEN p_type IN ('charge','load','acwr') THEN 'training_load'
    ELSE NULL END
$$;

DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname='supabase_realtime')
    AND NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname='supabase_realtime' AND schemaname='public' AND tablename='session_documents') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.session_documents;
  END IF;
END $$;

REVOKE ALL ON FUNCTION public.can_access_training_document(bigint) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.register_training_document(text,text,text,bigint,text,text[]) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.can_access_training_document_path(text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.can_access_session_document_link(integer,bigint) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.can_access_planning_event_document_link(bigint,bigint) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.publish_session_documents(integer,bigint[],integer[],text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.publish_session_document_distribution(integer,jsonb,text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.detach_session_document(integer,bigint) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.delete_document_transactional(bigint) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.publish_series_documents(bigint,bigint[],text,date) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.publish_planning_event_documents(bigint,bigint[],text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.can_access_training_document(bigint) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.register_training_document(text,text,text,bigint,text,text[]) TO authenticated;
GRANT EXECUTE ON FUNCTION public.can_access_training_document_path(text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.can_access_session_document_link(integer,bigint) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.can_access_planning_event_document_link(bigint,bigint) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.publish_session_documents(integer,bigint[],integer[],text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.publish_session_document_distribution(integer,jsonb,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.detach_session_document(integer,bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.delete_document_transactional(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.publish_series_documents(bigint,bigint[],text,date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.publish_planning_event_documents(bigint,bigint[],text) TO authenticated;

COMMIT;
