BEGIN;

CREATE TABLE IF NOT EXISTS public.wellness_questionnaire_versions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  club_id integer NOT NULL REFERENCES public.clubs(id) ON DELETE CASCADE,
  version_number integer NOT NULL,
  questions jsonb NOT NULL,
  active_days smallint[] NOT NULL DEFAULT ARRAY[1,2,3,4,5,6,7]::smallint[],
  response_visibility text NOT NULL DEFAULT 'staff',
  is_active boolean NOT NULL DEFAULT true,
  created_by integer NOT NULL REFERENCES public.users(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT wellness_questionnaire_versions_number_check CHECK (version_number > 0),
  CONSTRAINT wellness_questionnaire_versions_questions_check CHECK (jsonb_typeof(questions) = 'array'),
  CONSTRAINT wellness_questionnaire_versions_days_check CHECK (
    cardinality(active_days) BETWEEN 1 AND 7
    AND active_days <@ ARRAY[1,2,3,4,5,6,7]::smallint[]
  ),
  CONSTRAINT wellness_questionnaire_versions_visibility_check CHECK (response_visibility IN ('staff', 'head_coach')),
  UNIQUE (club_id, version_number)
);

CREATE UNIQUE INDEX IF NOT EXISTS wellness_questionnaire_one_active_per_club
  ON public.wellness_questionnaire_versions (club_id)
  WHERE is_active;

ALTER TABLE public.athlete_wellness
  ADD COLUMN IF NOT EXISTS questionnaire_version_id bigint REFERENCES public.wellness_questionnaire_versions(id) ON DELETE RESTRICT,
  ADD COLUMN IF NOT EXISTS answers jsonb NOT NULL DEFAULT '{}'::jsonb;

ALTER TABLE public.athlete_wellness
  DROP CONSTRAINT IF EXISTS athlete_wellness_answers_object_check;
ALTER TABLE public.athlete_wellness
  ADD CONSTRAINT athlete_wellness_answers_object_check CHECK (jsonb_typeof(answers) = 'object');

CREATE OR REPLACE FUNCTION public.default_wellness_questions()
RETURNS jsonb
LANGUAGE sql
IMMUTABLE
SET search_path TO 'public'
AS $$
  SELECT '[
    {"key":"sleep","required":true},
    {"key":"energy","required":true},
    {"key":"soreness","required":true},
    {"key":"mood","required":true},
    {"key":"stress","required":true}
  ]'::jsonb
$$;

ALTER TABLE public.wellness_questionnaire_versions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS wellness_questionnaire_staff_read ON public.wellness_questionnaire_versions;
CREATE POLICY wellness_questionnaire_staff_read ON public.wellness_questionnaire_versions
  FOR SELECT TO authenticated
  USING (club_id = public.get_my_club_id() AND public.get_my_role() IN ('head_coach', 'coach'));

DROP POLICY IF EXISTS athlete_wellness_coach_read ON public.athlete_wellness;
DROP POLICY IF EXISTS "athlete_wellness_coach_read" ON public.athlete_wellness;
CREATE POLICY athlete_wellness_coach_read ON public.athlete_wellness
  FOR SELECT TO authenticated
  USING (
    club_id = public.get_my_club_id()
    AND (
      public.get_my_role() = 'head_coach'
      OR (
        public.get_my_role() = 'coach'
        AND coalesce((
          SELECT version.response_visibility
          FROM public.wellness_questionnaire_versions version
          WHERE version.id = questionnaire_version_id
        ), 'staff') = 'staff'
      )
    )
  );

REVOKE INSERT, UPDATE, DELETE ON public.wellness_questionnaire_versions FROM authenticated;
REVOKE INSERT, UPDATE, DELETE ON public.athlete_wellness FROM authenticated;
GRANT SELECT ON public.wellness_questionnaire_versions TO authenticated;

CREATE OR REPLACE FUNCTION public.get_wellness_questionnaire(p_date date DEFAULT current_date)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_club_id integer := public.get_my_club_id();
  v_athlete_id integer := public.get_my_athlete_id();
  v_response_version_id bigint;
  v_version public.wellness_questionnaire_versions%ROWTYPE;
BEGIN
  IF v_club_id IS NULL OR public.get_my_role() NOT IN ('head_coach', 'coach', 'athlete') THEN
    RAISE EXCEPTION 'Action non autorisee.';
  END IF;

  IF v_athlete_id IS NOT NULL THEN
    SELECT questionnaire_version_id INTO v_response_version_id
    FROM public.athlete_wellness
    WHERE athlete_id = v_athlete_id AND date = p_date;
  END IF;

  IF v_response_version_id IS NOT NULL THEN
    SELECT * INTO v_version FROM public.wellness_questionnaire_versions
    WHERE id = v_response_version_id AND club_id = v_club_id;
  ELSE
    SELECT * INTO v_version FROM public.wellness_questionnaire_versions
    WHERE club_id = v_club_id AND is_active
    ORDER BY version_number DESC LIMIT 1;
  END IF;

  IF NOT FOUND THEN
    RETURN jsonb_build_object(
      'versionId', null,
      'versionNumber', 1,
      'questions', public.default_wellness_questions(),
      'activeDays', to_jsonb(ARRAY[1,2,3,4,5,6,7]::smallint[]),
      'responseVisibility', 'staff',
      'isDefault', true
    );
  END IF;

  RETURN jsonb_build_object(
    'versionId', v_version.id,
    'versionNumber', v_version.version_number,
    'questions', v_version.questions,
    'activeDays', to_jsonb(v_version.active_days),
    'responseVisibility', v_version.response_visibility,
    'isDefault', false
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.configure_wellness_questionnaire(
  p_questions jsonb,
  p_active_days smallint[],
  p_response_visibility text DEFAULT 'staff'
) RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_club_id integer := public.get_my_club_id();
  v_user_id integer := public.get_my_user_id();
  v_days smallint[] := ARRAY(
    SELECT DISTINCT day FROM unnest(coalesce(p_active_days, ARRAY[]::smallint[])) day ORDER BY day
  );
  v_version_number integer;
  v_id bigint;
BEGIN
  IF public.get_my_role() <> 'head_coach' OR v_club_id IS NULL OR v_user_id IS NULL THEN
    RAISE EXCEPTION 'Action reservee au head coach.';
  END IF;
  IF jsonb_typeof(p_questions) <> 'array' OR jsonb_array_length(p_questions) NOT BETWEEN 1 AND 12 THEN
    RAISE EXCEPTION 'Le questionnaire doit contenir entre 1 et 12 questions.';
  END IF;
  IF EXISTS (
    SELECT 1 FROM jsonb_array_elements(p_questions) question
    WHERE jsonb_typeof(question) <> 'object'
      OR NOT (question ? 'key')
      OR NOT (question ? 'required')
      OR jsonb_typeof(question->'required') <> 'boolean'
      OR question->>'key' NOT IN (
        'sleep','energy','soreness','mood','stress','motivation',
        'fatigue','pain','readiness','concentration','hydration','mental_load'
      )
  ) THEN
    RAISE EXCEPTION 'Une question ou un parametre est invalide.';
  END IF;
  IF (SELECT count(*) FROM jsonb_array_elements(p_questions)) <> (
    SELECT count(DISTINCT question->>'key') FROM jsonb_array_elements(p_questions) question
  ) THEN
    RAISE EXCEPTION 'Une question ne peut apparaitre qu une seule fois.';
  END IF;
  IF cardinality(v_days) NOT BETWEEN 1 AND 7 OR NOT (v_days <@ ARRAY[1,2,3,4,5,6,7]::smallint[]) THEN
    RAISE EXCEPTION 'Les jours du questionnaire sont invalides.';
  END IF;
  IF p_response_visibility NOT IN ('staff', 'head_coach') THEN
    RAISE EXCEPTION 'Visibilite des reponses invalide.';
  END IF;

  PERFORM 1 FROM public.clubs WHERE id = v_club_id FOR UPDATE;
  SELECT coalesce(max(version_number), 0) + 1 INTO v_version_number
  FROM public.wellness_questionnaire_versions WHERE club_id = v_club_id;
  UPDATE public.wellness_questionnaire_versions SET is_active = false
  WHERE club_id = v_club_id AND is_active;
  INSERT INTO public.wellness_questionnaire_versions (
    club_id, version_number, questions, active_days, response_visibility, is_active, created_by
  ) VALUES (
    v_club_id, v_version_number, p_questions, v_days, p_response_visibility, true, v_user_id
  ) RETURNING id INTO v_id;

  UPDATE public.club_modules
  SET config = coalesce(config, '{}'::jsonb) || jsonb_build_object('wellnessQuestionnaireVersionId', v_id),
      updated_by = v_user_id,
      updated_at = now()
  WHERE club_id = v_club_id AND module_key = 'wellness';

  RETURN jsonb_build_object('versionId', v_id, 'versionNumber', v_version_number);
END;
$$;

CREATE OR REPLACE FUNCTION public.submit_wellness_response(
  p_answers jsonb,
  p_notes text DEFAULT NULL,
  p_date date DEFAULT current_date
) RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_athlete_id integer := public.get_my_athlete_id();
  v_club_id integer := public.get_my_club_id();
  v_existing public.athlete_wellness%ROWTYPE;
  v_version public.wellness_questionnaire_versions%ROWTYPE;
  v_questions jsonb;
  v_answers jsonb := jsonb_strip_nulls(coalesce(p_answers, '{}'::jsonb));
  v_version_id bigint;
  v_id bigint;
BEGIN
  IF public.get_my_role() <> 'athlete' OR v_athlete_id IS NULL OR v_club_id IS NULL THEN
    RAISE EXCEPTION 'Action reservee a l athlete.';
  END IF;
  IF jsonb_typeof(v_answers) <> 'object' THEN RAISE EXCEPTION 'Format de reponse invalide.'; END IF;
  IF p_date < current_date - 1 OR p_date > current_date THEN
    RAISE EXCEPTION 'La date du questionnaire est invalide.';
  END IF;
  SELECT * INTO v_existing FROM public.athlete_wellness
  WHERE athlete_id = v_athlete_id AND date = p_date FOR UPDATE;

  IF FOUND AND v_existing.questionnaire_version_id IS NULL THEN
    v_questions := public.default_wellness_questions();
    v_version_id := null;
  ELSIF FOUND THEN
    SELECT * INTO v_version FROM public.wellness_questionnaire_versions
    WHERE id = v_existing.questionnaire_version_id AND club_id = v_club_id;
    IF NOT FOUND THEN RAISE EXCEPTION 'Version de questionnaire introuvable.'; END IF;
    v_questions := v_version.questions;
    v_version_id := v_version.id;
  ELSE
    SELECT * INTO v_version FROM public.wellness_questionnaire_versions
    WHERE club_id = v_club_id AND is_active ORDER BY version_number DESC LIMIT 1;
    IF FOUND THEN
      v_questions := v_version.questions;
      v_version_id := v_version.id;
    ELSE
      v_questions := public.default_wellness_questions();
      v_version_id := null;
    END IF;
  END IF;

  IF EXISTS (
    SELECT 1 FROM jsonb_each(v_answers) answer
    WHERE answer.key NOT IN (SELECT question->>'key' FROM jsonb_array_elements(v_questions) question)
      OR jsonb_typeof(answer.value) <> 'number'
      OR (answer.value #>> '{}')::numeric <> trunc((answer.value #>> '{}')::numeric)
      OR (answer.value #>> '{}')::integer NOT BETWEEN 1 AND 5
  ) THEN
    RAISE EXCEPTION 'Une reponse est invalide.';
  END IF;
  IF EXISTS (
    SELECT 1 FROM jsonb_array_elements(v_questions) question
    WHERE (question->>'required')::boolean
      AND NOT (v_answers ? (question->>'key'))
  ) THEN
    RAISE EXCEPTION 'Toutes les questions obligatoires doivent etre completees.';
  END IF;
  IF char_length(coalesce(p_notes, '')) > 2000 THEN RAISE EXCEPTION 'La note est trop longue.'; END IF;

  INSERT INTO public.athlete_wellness (
    athlete_id, club_id, date, sleep, energy, soreness, mood, stress, notes,
    questionnaire_version_id, answers
  ) VALUES (
    v_athlete_id, v_club_id, p_date,
    nullif(v_answers->>'sleep', '')::integer,
    nullif(v_answers->>'energy', '')::integer,
    nullif(v_answers->>'soreness', '')::integer,
    nullif(v_answers->>'mood', '')::integer,
    nullif(v_answers->>'stress', '')::integer,
    nullif(btrim(p_notes), ''), v_version_id, v_answers
  )
  ON CONFLICT (athlete_id, date) DO UPDATE SET
    sleep = EXCLUDED.sleep,
    energy = EXCLUDED.energy,
    soreness = EXCLUDED.soreness,
    mood = EXCLUDED.mood,
    stress = EXCLUDED.stress,
    notes = EXCLUDED.notes,
    answers = EXCLUDED.answers
  RETURNING id INTO v_id;

  RETURN jsonb_build_object(
    'wellnessId', v_id,
    'questionnaireVersionId', v_version_id,
    'date', p_date,
    'answers', v_answers
  );
END;
$$;

REVOKE ALL ON FUNCTION public.default_wellness_questions() FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.get_wellness_questionnaire(date) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.configure_wellness_questionnaire(jsonb, smallint[], text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.submit_wellness_response(jsonb, text, date) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_wellness_questionnaire(date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.configure_wellness_questionnaire(jsonb, smallint[], text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.submit_wellness_response(jsonb, text, date) TO authenticated;

COMMIT;
